# ------------------------------------------------------------------------------
# EnergyStorageType ::= BIT STRING {hydrogenStorage(0), electricEnergyStorage(1), liquidPropaneGas(2), compressedNaturalGas(3), diesel(4), gasoline(5), ammonia(6)} (SIZE(7))
# ------------------------------------------------------------------------------

# named-bits: [('hydrogenStorage', '0'), ('electricEnergyStorage', '1'), ('liquidPropaneGas', '2'), ('compressedNaturalGas', '3'), ('diesel', '4'), ('gasoline', '5'), ('ammonia', '6')]
# size: [7]
string value
