/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=spatem_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_spatem_ts_DDateTime_H_
#define	_spatem_ts_DDateTime_H_


#include <etsi_its_spatem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_spatem_ts_coding/spatem_ts_DYear.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_DMonth.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_DDay.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_DHour.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_DMinute.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_DSecond.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_DOffset.h"
#include <etsi_its_spatem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* spatem_ts_DDateTime */
typedef struct spatem_ts_DDateTime {
	spatem_ts_DYear_t	*year;	/* OPTIONAL */
	spatem_ts_DMonth_t	*month;	/* OPTIONAL */
	spatem_ts_DDay_t	*day;	/* OPTIONAL */
	spatem_ts_DHour_t	*hour;	/* OPTIONAL */
	spatem_ts_DMinute_t	*minute;	/* OPTIONAL */
	spatem_ts_DSecond_t	*second;	/* OPTIONAL */
	spatem_ts_DOffset_t	*offset;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} spatem_ts_DDateTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_spatem_ts_DDateTime;
extern asn_SEQUENCE_specifics_t asn_SPC_spatem_ts_DDateTime_specs_1;
extern asn_TYPE_member_t asn_MBR_spatem_ts_DDateTime_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _spatem_ts_DDateTime_H_ */
#include <etsi_its_spatem_ts_coding/asn_internal.h>
