/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ElectronicRegistrationIdentificationVehicleDataModule"
 * 	found in "/input/ISO24534-3_ElectronicRegistrationIdentificationVehicleDataModule-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=spatem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_spatem_ts_EuVehicleCategoryCode_H_
#define	_spatem_ts_EuVehicleCategoryCode_H_


#include <etsi_its_spatem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_spatem_ts_coding/spatem_ts_EuVehicleCategoryL.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_EuVehicleCategoryM.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_EuVehicleCategoryN.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_EuVehicleCategoryO.h"
#include <etsi_its_spatem_ts_coding/NULL.h>
#include <etsi_its_spatem_ts_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum spatem_ts_EuVehicleCategoryCode_PR {
	spatem_ts_EuVehicleCategoryCode_PR_NOTHING,	/* No components present */
	spatem_ts_EuVehicleCategoryCode_PR_euVehicleCategoryL,
	spatem_ts_EuVehicleCategoryCode_PR_euVehicleCategoryM,
	spatem_ts_EuVehicleCategoryCode_PR_euVehicleCategoryN,
	spatem_ts_EuVehicleCategoryCode_PR_euVehicleCategoryO,
	spatem_ts_EuVehicleCategoryCode_PR_euVehilcleCategoryT,
	spatem_ts_EuVehicleCategoryCode_PR_euVehilcleCategoryG
} spatem_ts_EuVehicleCategoryCode_PR;

/* spatem_ts_EuVehicleCategoryCode */
typedef struct spatem_ts_EuVehicleCategoryCode {
	spatem_ts_EuVehicleCategoryCode_PR present;
	union spatem_ts_EuVehicleCategoryCode_u {
		spatem_ts_EuVehicleCategoryL_t	 euVehicleCategoryL;
		spatem_ts_EuVehicleCategoryM_t	 euVehicleCategoryM;
		spatem_ts_EuVehicleCategoryN_t	 euVehicleCategoryN;
		spatem_ts_EuVehicleCategoryO_t	 euVehicleCategoryO;
		NULL_t	 euVehilcleCategoryT;
		NULL_t	 euVehilcleCategoryG;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} spatem_ts_EuVehicleCategoryCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_spatem_ts_EuVehicleCategoryCode;

#ifdef __cplusplus
}
#endif

#endif	/* _spatem_ts_EuVehicleCategoryCode_H_ */
#include <etsi_its_spatem_ts_coding/asn_internal.h>
