/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=spatem_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_spatem_ts_IntersectionState_H_
#define	_spatem_ts_IntersectionState_H_


#include <etsi_its_spatem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_spatem_ts_coding/spatem_ts_DescriptiveName.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_IntersectionReferenceID.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_MsgCount.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_IntersectionStatusObject.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_MinuteOfTheYear.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_DSecond.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_MovementList.h"
#include <etsi_its_spatem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_spatem_ts_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_spatem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct spatem_ts_EnabledLaneList;
struct spatem_ts_ManeuverAssistList;
struct spatem_ts_Reg_IntersectionState;

/* spatem_ts_IntersectionState */
typedef struct spatem_ts_IntersectionState {
	spatem_ts_DescriptiveName_t	*name;	/* OPTIONAL */
	spatem_ts_IntersectionReferenceID_t	 id;
	spatem_ts_MsgCount_t	 revision;
	spatem_ts_IntersectionStatusObject_t	 status;
	spatem_ts_MinuteOfTheYear_t	*moy;	/* OPTIONAL */
	spatem_ts_DSecond_t	*timeStamp;	/* OPTIONAL */
	struct spatem_ts_EnabledLaneList	*enabledLanes;	/* OPTIONAL */
	spatem_ts_MovementList_t	 states;
	struct spatem_ts_ManeuverAssistList	*maneuverAssistList;	/* OPTIONAL */
	struct spatem_ts_IntersectionState__regional {
		A_SEQUENCE_OF(struct spatem_ts_Reg_IntersectionState) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} spatem_ts_IntersectionState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_spatem_ts_IntersectionState;
extern asn_SEQUENCE_specifics_t asn_SPC_spatem_ts_IntersectionState_specs_1;
extern asn_TYPE_member_t asn_MBR_spatem_ts_IntersectionState_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_spatem_ts_coding/spatem_ts_EnabledLaneList.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_ManeuverAssistList.h"
#include "etsi_its_spatem_ts_coding/spatem_ts_RegionalExtension.h"

#endif	/* _spatem_ts_IntersectionState_H_ */
#include <etsi_its_spatem_ts_coding/asn_internal.h>
