/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EV-RechargingSpotReservation-PDU-Descriptions"
 * 	found in "/input/EV-RSR-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -gen-PER`
 */

#include "CancellationRequestMessage.h"

asn_TYPE_member_t asn_MBR_CancellationRequestMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CancellationRequestMessage, reservation_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Reservation_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reservation-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CancellationRequestMessage, reservation_Password),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Reservation_Password,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reservation-Password"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CancellationRequestMessage, currentTime),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimestampUTC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"currentTime"
		},
};
static const ber_tlv_tag_t asn_DEF_CancellationRequestMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CancellationRequestMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* reservation-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* reservation-Password */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* currentTime */
};
asn_SEQUENCE_specifics_t asn_SPC_CancellationRequestMessage_specs_1 = {
	sizeof(struct CancellationRequestMessage),
	offsetof(struct CancellationRequestMessage, _asn_ctx),
	asn_MAP_CancellationRequestMessage_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CancellationRequestMessage = {
	"CancellationRequestMessage",
	"CancellationRequestMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_CancellationRequestMessage_tags_1,
	sizeof(asn_DEF_CancellationRequestMessage_tags_1)
		/sizeof(asn_DEF_CancellationRequestMessage_tags_1[0]), /* 1 */
	asn_DEF_CancellationRequestMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_CancellationRequestMessage_tags_1)
		/sizeof(asn_DEF_CancellationRequestMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CancellationRequestMessage_1,
	3,	/* Elements count */
	&asn_SPC_CancellationRequestMessage_specs_1	/* Additional specs */
};

