/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EV-RechargingSpotReservation-PDU-Descriptions"
 * 	found in "/input/EV-RSR-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -gen-PER`
 */

#include "PreReservationRequestMessage.h"

asn_TYPE_member_t asn_MBR_PreReservationRequestMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PreReservationRequestMessage, evse_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EVSE_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"evse-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PreReservationRequestMessage, arrivalTime),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimestampUTC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"arrivalTime"
		},
	{ ATF_POINTER, 1, offsetof(struct PreReservationRequestMessage, departureTime),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimestampUTC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"departureTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PreReservationRequestMessage, rechargingType),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RechargingType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rechargingType"
		},
	{ ATF_POINTER, 1, offsetof(struct PreReservationRequestMessage, batteryType),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BatteryType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"batteryType"
		},
};
static const int asn_MAP_PreReservationRequestMessage_oms_1[] = { 2, 4 };
static const ber_tlv_tag_t asn_DEF_PreReservationRequestMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PreReservationRequestMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* evse-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* arrivalTime */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* departureTime */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* rechargingType */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* batteryType */
};
asn_SEQUENCE_specifics_t asn_SPC_PreReservationRequestMessage_specs_1 = {
	sizeof(struct PreReservationRequestMessage),
	offsetof(struct PreReservationRequestMessage, _asn_ctx),
	asn_MAP_PreReservationRequestMessage_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_PreReservationRequestMessage_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PreReservationRequestMessage = {
	"PreReservationRequestMessage",
	"PreReservationRequestMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_PreReservationRequestMessage_tags_1,
	sizeof(asn_DEF_PreReservationRequestMessage_tags_1)
		/sizeof(asn_DEF_PreReservationRequestMessage_tags_1[0]), /* 1 */
	asn_DEF_PreReservationRequestMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_PreReservationRequestMessage_tags_1)
		/sizeof(asn_DEF_PreReservationRequestMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PreReservationRequestMessage_1,
	5,	/* Elements count */
	&asn_SPC_PreReservationRequestMessage_specs_1	/* Additional specs */
};

