# ------------------------------------------------------------------------------
{% for line in asn1_definition.split('\n') -%}
# {{ line }}
{% endfor -%}
# ------------------------------------------------------------------------------

{% for comment in comments -%}
# {{ comment }}
{% endfor -%}
{% for member in members -%}
{{ member.type }} {{ member.name }}
{% if member.optional -%}
bool {{ member.name }}_isPresent
{% endif -%}
{% for const in member.constants -%}
{{ const.type }} {{ const.name }} = {{ const.value }}
{% endfor %}
{% endfor %}