/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/is_ts103301/IVIM-PDU-Descriptions.asn \
  asn1/raw/is_ts103301/cdd/ITS-Container.asn \
  asn1/raw/is_ts103301/iso-patched/ISO24534-3_ElectronicRegistrationIdentificationVehicleDataModule-patched.asn \
  asn1/raw/is_ts103301/iso-patched/ISO14823-missing.asn \
  asn1/raw/is_ts103301/build/asn1/TS17419_2014_CITSapplMgmtIDs.asn \
  asn1/raw/is_ts103301/iso-patched/ISO14906(2018)EfcDsrcGenericv7-patched.asn \
  asn1/raw/is_ts103301/iso-patched/ISO14906(2018)EfcDsrcApplicationv6-patched.asn \
  asn1/raw/is_ts103301/build/asn1/ISO-TS-19091-addgrp-C-2018-patched.asn \
  asn1/patched/is_ts103301/build/asn1/ISO14816_AVIAEINumberingAndDataStructures.asn \
  asn1/raw/is_ts103301/build/asn1/ISO19321IVIv2.asn \
  -t \
  ivim_ts \
  -o \
  etsi_its_conversion/etsi_its_ivim_ts_conversion/include/etsi_its_ivim_ts_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
RSCode::= SEQUENCE{
	layoutComponentId	INTEGER(1..4,...) OPTIONAL,
	code				CHOICE {
		viennaConvention	VcCode, -- see Vienna Convention Annex A
		iso14823			ISO14823Code, 
		itisCodes			INTEGER (0..65535), -- see SAE J2540
		anyCatalogue		AnyCatalogue,
		...
		}}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_ivim_ts_coding/ivim_ts_RSCode.h>
#include <etsi_its_ivim_ts_conversion/convertAnyCatalogue.h>
#include <etsi_its_ivim_ts_coding/INTEGER.h>
#include <etsi_its_primitives_conversion/convertINTEGER.h>
#include <etsi_its_ivim_ts_conversion/convertISO14823Code.h>
#include <etsi_its_ivim_ts_conversion/convertVcCode.h>
#include <etsi_its_ivim_ts_msgs/msg/rs_code.hpp>
namespace ivim_ts_msgs = etsi_its_ivim_ts_msgs::msg;


namespace etsi_its_ivim_ts_conversion {

void toRos_RSCode(const ivim_ts_RSCode_t& in, ivim_ts_msgs::RSCode& out) {
  if (in.layoutComponentId) {
    etsi_its_primitives_conversion::toRos_INTEGER(*in.layoutComponentId, out.layout_component_id);
    out.layout_component_id_is_present = true;
  }
  if (in.code.present == ivim_ts_RSCode__code_PR_viennaConvention) {
    toRos_VcCode(in.code.choice.viennaConvention, out.code_vienna_convention);
    out.code_choice = ivim_ts_msgs::RSCode::CHOICE_CODE_VIENNA_CONVENTION;
  }
  if (in.code.present == ivim_ts_RSCode__code_PR_iso14823) {
    toRos_ISO14823Code(in.code.choice.iso14823, out.code_iso14823);
    out.code_choice = ivim_ts_msgs::RSCode::CHOICE_CODE_ISO14823;
  }
  etsi_its_primitives_conversion::toRos_INTEGER(in.code.choice.itisCodes, out.code_itis_codes);
  if (in.code.present == ivim_ts_RSCode__code_PR_anyCatalogue) {
    toRos_AnyCatalogue(in.code.choice.anyCatalogue, out.code_any_catalogue);
    out.code_choice = ivim_ts_msgs::RSCode::CHOICE_CODE_ANY_CATALOGUE;
  }
}

void toStruct_RSCode(const ivim_ts_msgs::RSCode& in, ivim_ts_RSCode_t& out) {
  memset(&out, 0, sizeof(ivim_ts_RSCode_t));
  if (in.layout_component_id_is_present) {
    out.layoutComponentId = (long*) calloc(1, sizeof(long));
    etsi_its_primitives_conversion::toStruct_INTEGER(in.layout_component_id, *out.layoutComponentId);
  }
  if (in.code_choice == ivim_ts_msgs::RSCode::CHOICE_CODE_VIENNA_CONVENTION) {
    toStruct_VcCode(in.code_vienna_convention, out.code.choice.viennaConvention);
    out.code.present = ivim_ts_RSCode__code_PR_viennaConvention;
  }
  if (in.code_choice == ivim_ts_msgs::RSCode::CHOICE_CODE_ISO14823) {
    toStruct_ISO14823Code(in.code_iso14823, out.code.choice.iso14823);
    out.code.present = ivim_ts_RSCode__code_PR_iso14823;
  }
  etsi_its_primitives_conversion::toStruct_INTEGER(in.code_itis_codes, out.code.choice.itisCodes);
  if (in.code_choice == ivim_ts_msgs::RSCode::CHOICE_CODE_ANY_CATALOGUE) {
    toStruct_AnyCatalogue(in.code_any_catalogue, out.code.choice.anyCatalogue);
    out.code.present = ivim_ts_RSCode__code_PR_anyCatalogue;
  }
}

}
