# ------------------------------------------------------------------------------
# AccelerationConfidence ::= INTEGER {pointOneMeterPerSecSquared(1), outOfRange(101), unavailable(102)} (0 .. 102)
# ------------------------------------------------------------------------------

# restricted-to: [(0, 102)]
uint8 POINT_ONE_METER_PER_SEC_SQUARED = 1
uint8 OUT_OF_RANGE = 101
uint8 UNAVAILABLE = 102
uint8 value
