# ------------------------------------------------------------------------------
# AdverseWeatherCondition-VisibilitySubCauseCode ::= INTEGER {unavailable(0), fog(1), smoke(2), heavySnowfall(3), heavyRain(4), heavyHail(5), lowSunGlare(6), sandstorms(7), swarmsOfInsects(8)} (0..255)
# ------------------------------------------------------------------------------

# restricted-to: [(0, 255)]
uint8 UNAVAILABLE = 0
uint8 FOG = 1
uint8 SMOKE = 2
uint8 HEAVY_SNOWFALL = 3
uint8 HEAVY_RAIN = 4
uint8 HEAVY_HAIL = 5
uint8 LOW_SUN_GLARE = 6
uint8 SANDSTORMS = 7
uint8 SWARMS_OF_INSECTS = 8
uint8 value
