# ------------------------------------------------------------------------------
# DeltaAltitude ::= INTEGER {oneCentimeterUp (1), oneCentimeterDown (-1), unavailable(12800)} (-12700..12800)
# ------------------------------------------------------------------------------

# restricted-to: [(-12700, 12800)]
int16 ONE_CENTIMETER_UP = 1
int16 ONE_CENTIMETER_DOWN = -1
int16 UNAVAILABLE = 12800
int16 value
