# ------------------------------------------------------------------------------
# DeltaReferencePosition ::= SEQUENCE {
#     deltaLatitude DeltaLatitude,
#     deltaLongitude DeltaLongitude,
#     deltaAltitude DeltaAltitude
# }
# ------------------------------------------------------------------------------

DeltaLatitude deltaLatitude

DeltaLongitude deltaLongitude

DeltaAltitude deltaAltitude
