# ------------------------------------------------------------------------------
# LongitudinalAcceleration ::= SEQUENCE {
#     longitudinalAccelerationValue LongitudinalAccelerationValue,
#     longitudinalAccelerationConfidence AccelerationConfidence
# }
# ------------------------------------------------------------------------------

LongitudinalAccelerationValue longitudinalAccelerationValue

AccelerationConfidence longitudinalAccelerationConfidence
