# ------------------------------------------------------------------------------
# RelevanceDistance ::= ENUMERATED {lessThan50m(0), lessThan100m(1), lessThan200m(2), lessThan500m(3), lessThan1000m(4), lessThan5km(5), lessThan10km(6), over10km(7)}
# ------------------------------------------------------------------------------

uint8 LESS_THAN_5_0M = 0
uint8 LESS_THAN_1_0_0M = 1
uint8 LESS_THAN_2_0_0M = 2
uint8 LESS_THAN_5_0_0M = 3
uint8 LESS_THAN_1_0_0_0M = 4
uint8 LESS_THAN_5KM = 5
uint8 LESS_THAN_1_0KM = 6
uint8 OVER_1_0KM = 7
uint8 value
