# ------------------------------------------------------------------------------
# StationarySince ::= ENUMERATED {lessThan1Minute(0), lessThan2Minutes(1), lessThan15Minutes(2), equalOrGreater15Minutes(3)}
# ------------------------------------------------------------------------------

uint8 LESS_THAN_1_MINUTE = 0
uint8 LESS_THAN_2_MINUTES = 1
uint8 LESS_THAN_1_5_MINUTES = 2
uint8 EQUAL_OR_GREATER_1_5_MINUTES = 3
uint8 value
