# ------------------------------------------------------------------------------
# Temperature ::= INTEGER {equalOrSmallerThanMinus60Deg (-60), oneDegreeCelsius(1), equalOrGreaterThan67Deg(67)} (-60..67)
# ------------------------------------------------------------------------------

# restricted-to: [(-60, 67)]
int8 EQUAL_OR_SMALLER_THAN_MINUS_6_0_DEG = -60
int8 ONE_DEGREE_CELSIUS = 1
int8 EQUAL_OR_GREATER_THAN_6_7_DEG = 67
int8 value
