# ------------------------------------------------------------------------------
# VehicleLength ::= SEQUENCE {
#     vehicleLengthValue VehicleLengthValue,
#     vehicleLengthConfidenceIndication VehicleLengthConfidenceIndication
# }
# ------------------------------------------------------------------------------

VehicleLengthValue vehicleLengthValue

VehicleLengthConfidenceIndication vehicleLengthConfidenceIndication
