# ------------------------------------------------------------------------------
# PositionalAccuracy ::= SEQUENCE {
#    semiMajor     SemiMajorAxisAccuracy,
#    semiMinor     SemiMinorAxisAccuracy,
#    orientation   SemiMajorAxisOrientation
# }
# ------------------------------------------------------------------------------

SemiMajorAxisAccuracy semiMajor

SemiMinorAxisAccuracy semiMinor

SemiMajorAxisOrientation orientation
