# ------------------------------------------------------------------------------
# RequestImportanceLevel ::= ENUMERATED {
#   requestImportanceLevelUnKnown  (0),
#   requestImportanceLevel1        (1),
#   requestImportanceLevel2        (2),
#   requestImportanceLevel3        (3),
#   requestImportanceLevel4        (4),
#   requestImportanceLevel5        (5),
#   requestImportanceLevel6        (6),
#   requestImportanceLevel7        (7),
#   requestImportanceLevel8        (8),
#   requestImportanceLevel9        (9),
#   requestImportanceLevel10      (10),
#   requestImportanceLevel11      (11),
#   requestImportanceLevel12      (12),
#   requestImportanceLevel13      (13),
#   requestImportanceLevel14      (14),
#   requestImportanceReserved     (15)
# }
# ------------------------------------------------------------------------------

uint8 REQUEST_IMPORTANCE_LEVEL_UN_KNOWN = 0
uint8 REQUEST_IMPORTANCE_LEVEL_1 = 1
uint8 REQUEST_IMPORTANCE_LEVEL_2 = 2
uint8 REQUEST_IMPORTANCE_LEVEL_3 = 3
uint8 REQUEST_IMPORTANCE_LEVEL_4 = 4
uint8 REQUEST_IMPORTANCE_LEVEL_5 = 5
uint8 REQUEST_IMPORTANCE_LEVEL_6 = 6
uint8 REQUEST_IMPORTANCE_LEVEL_7 = 7
uint8 REQUEST_IMPORTANCE_LEVEL_8 = 8
uint8 REQUEST_IMPORTANCE_LEVEL_9 = 9
uint8 REQUEST_IMPORTANCE_LEVEL_1_0 = 10
uint8 REQUEST_IMPORTANCE_LEVEL_1_1 = 11
uint8 REQUEST_IMPORTANCE_LEVEL_1_2 = 12
uint8 REQUEST_IMPORTANCE_LEVEL_1_3 = 13
uint8 REQUEST_IMPORTANCE_LEVEL_1_4 = 14
uint8 REQUEST_IMPORTANCE_RESERVED = 15
uint8 value
