# ------------------------------------------------------------------------------
# SpeedandHeadingandThrottleConfidence ::= SEQUENCE {
#    heading   HeadingConfidence,    
#    speed     SpeedConfidence,      
#    throttle  ThrottleConfidence    
#    }
# ------------------------------------------------------------------------------

HeadingConfidence heading

SpeedConfidence speed

ThrottleConfidence throttle
