# ------------------------------------------------------------------------------
# TransitVehicleStatus ::= BIT STRING {
#   loading     (0),
#   anADAuse    (1),
#   aBikeLoad   (2),
#   doorOpen    (3),
#   charging    (4),
#   atStopLine  (5)
# } (SIZE(8))
# ------------------------------------------------------------------------------

# named-bits: [('loading', '0'), ('anADAuse', '1'), ('aBikeLoad', '2'), ('doorOpen', '3'), ('charging', '4'), ('atStopLine', '5')]
# size: [8]
string value
