# ------------------------------------------------------------------------------
# TransmissionState ::= ENUMERATED {
#   neutral      (0),
#   park         (1),
#   forwardGears (2),
#   reverseGears (3),
#   reserved1    (4),      
#   reserved2    (5),      
#   reserved3    (6),      
#   unavailable  (7)
# }
# ------------------------------------------------------------------------------

uint8 NEUTRAL = 0
uint8 PARK = 1
uint8 FORWARD_GEARS = 2
uint8 REVERSE_GEARS = 3
uint8 RESERVED_1 = 4
uint8 RESERVED_2 = 5
uint8 RESERVED_3 = 6
uint8 UNAVAILABLE = 7
uint8 value
