# ------------------------------------------------------------------------------
# ThrottleConfidence ::= ENUMERATED {
#    unavailable     (0),
#    prec10percent   (1),
#    prec1percent    (2),
#    prec0-5percent  (3)
#    }
# ------------------------------------------------------------------------------

uint8 UNAVAILABLE = 0
uint8 PREC_1_0PERCENT = 1
uint8 PREC_1PERCENT = 2
uint8 PREC_0_5PERCENT = 3
uint8 value
