## SEQUENCE BasicVehicleContainerHighFrequency 

Heading heading


Speed speed


DriveDirection drive_direction


VehicleLength vehicle_length


VehicleWidth vehicle_width


LongitudinalAcceleration longitudinal_acceleration


Curvature curvature


CurvatureCalculationMode curvature_calculation_mode


YawRate yaw_rate


bool acceleration_control_is_present
AccelerationControl acceleration_control


bool lane_position_is_present
LanePosition lane_position


bool steering_wheel_angle_is_present
SteeringWheelAngle steering_wheel_angle


bool lateral_acceleration_is_present
LateralAcceleration lateral_acceleration


bool vertical_acceleration_is_present
VerticalAcceleration vertical_acceleration


bool performance_class_is_present
PerformanceClass performance_class


bool cen_dsrc_tolling_zone_is_present
CenDsrcTollingZone cen_dsrc_tolling_zone






