# ------------------------------------------------------------------------------
# LaneAttributes-addGrpC ::= SEQUENCE {
#   maxVehicleHeight  VehicleHeight OPTIONAL,
#   maxVehicleWeight  VehicleMass   OPTIONAL,
#   ...
# }
# ------------------------------------------------------------------------------

# optional: True
VehicleHeight maxVehicleHeight

# optional: True
VehicleMass maxVehicleWeight
