# ------------------------------------------------------------------------------
#  LowFrequencyContainer ::= CHOICE {
#   basicVehicleContainerLowFrequency BasicVehicleContainerLowFrequency,
# 	...
# }
# ------------------------------------------------------------------------------

uint8 choice

BasicVehicleContainerLowFrequency basicVehicleContainerLowFrequency
uint8 CHOICE_BASIC_VEHICLE_CONTAINER_LOW_FREQUENCY = 0

