# ------------------------------------------------------------------------------
#  RoadWorksContainerBasic ::= SEQUENCE {
#   roadworksSubCauseCode RoadworksSubCauseCode OPTIONAL,
#   lightBarSirenInUse LightBarSirenInUse,
#   closedLanes ClosedLanes OPTIONAL
#  }
# ------------------------------------------------------------------------------

RoadworksSubCauseCode roadworks_sub_cause_code
bool roadworks_sub_cause_code_is_present

LightBarSirenInUse light_bar_siren_in_use

ClosedLanes closed_lanes
bool closed_lanes_is_present

