# ------------------------------------------------------------------------------
#  RoadWorksContainerBasic ::= SEQUENCE {
#   roadworksSubCauseCode RoadworksSubCauseCode OPTIONAL,
#   lightBarSirenInUse LightBarSirenInUse,
#   closedLanes ClosedLanes OPTIONAL
#  }
# ------------------------------------------------------------------------------

RoadworksSubCauseCode roadworksSubCauseCode
bool roadworksSubCauseCode_isPresent

LightBarSirenInUse lightBarSirenInUse

ClosedLanes closedLanes
bool closedLanes_isPresent

