# ------------------------------------------------------------------------------
# RSUContainerHighFrequency ::= SEQUENCE {
# 	protectedCommunicationZonesRSU ProtectedCommunicationZonesRSU OPTIONAL,
# 	...
# }
# ------------------------------------------------------------------------------

ProtectedCommunicationZonesRSU protected_communication_zones_rsu
bool protected_communication_zones_rsu_is_present

