# ------------------------------------------------------------------------------
# RSUContainerHighFrequency ::= SEQUENCE {
# 	protectedCommunicationZonesRSU ProtectedCommunicationZonesRSU OPTIONAL,
# 	...
# }
# ------------------------------------------------------------------------------

ProtectedCommunicationZonesRSU protected_communication_zones_r_s_u
bool protected_communication_zones_r_s_u_is_present

