# ------------------------------------------------------------------------------
# SignalStatusPackage-addGrpC ::= SEQUENCE {
#   synchToSchedule  DeltaTime      OPTIONAL,
#   rejectedReason   RejectedReason OPTIONAL,
#   ...
# }
# ------------------------------------------------------------------------------

# optional: True
DeltaTime synchToSchedule

# optional: True
RejectedReason rejectedReason
