/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -no-gen-example -gen-UPER`
 */


/* Including external dependencies */
#include <etsi_its_mapem_coding/constr_SEQUENCE.h>
#ifndef	_ConnectionManeuverAssist_addGrpC_H_
#define	_ConnectionManeuverAssist_addGrpC_H_


#include <etsi_its_mapem_coding/asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ItsStationPositionList;

/* ConnectionManeuverAssist-addGrpC */
typedef struct ConnectionManeuverAssist_addGrpC {
	struct ItsStationPositionList	*itsStationPosition;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConnectionManeuverAssist_addGrpC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnectionManeuverAssist_addGrpC;
extern asn_SEQUENCE_specifics_t asn_SPC_ConnectionManeuverAssist_addGrpC_specs_1;
extern asn_TYPE_member_t asn_MBR_ConnectionManeuverAssist_addGrpC_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mapem_coding/ItsStationPositionList.h"

#endif	/* _ConnectionManeuverAssist_addGrpC_H_ */
#include <etsi_its_mapem_coding/asn_internal.h>
