/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "AVIAEINumberingAndDataStructures"
 * 	found in "/input/ISO14816_AVIAEINumberingAndDataStructures.asn"
 * 	`asn1c -fcompound-names -no-gen-example -gen-UPER`
 */


/* Including external dependencies */
#include <etsi_its_mapem_coding/NativeInteger.h>
#ifndef	_IssuerIdentifier_H_
#define	_IssuerIdentifier_H_


#include <etsi_its_mapem_coding/asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IssuerIdentifier */
typedef long	 IssuerIdentifier_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_IssuerIdentifier_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_IssuerIdentifier;
asn_struct_free_f IssuerIdentifier_free;
asn_struct_print_f IssuerIdentifier_print;
asn_constr_check_f IssuerIdentifier_constraint;
ber_type_decoder_f IssuerIdentifier_decode_ber;
der_type_encoder_f IssuerIdentifier_encode_der;
xer_type_decoder_f IssuerIdentifier_decode_xer;
xer_type_encoder_f IssuerIdentifier_encode_xer;
jer_type_encoder_f IssuerIdentifier_encode_jer;
oer_type_decoder_f IssuerIdentifier_decode_oer;
oer_type_encoder_f IssuerIdentifier_encode_oer;
per_type_decoder_f IssuerIdentifier_decode_uper;
per_type_encoder_f IssuerIdentifier_encode_uper;
per_type_decoder_f IssuerIdentifier_decode_aper;
per_type_encoder_f IssuerIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _IssuerIdentifier_H_ */
#include <etsi_its_mapem_coding/asn_internal.h>
