/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "/input/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=cam_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_cam_BasicVehicleContainerLowFrequency_H_
#define	_cam_BasicVehicleContainerLowFrequency_H_


#include <etsi_its_cam_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_cam_coding/cam_VehicleRole.h"
#include "etsi_its_cam_coding/cam_ExteriorLights.h"
#include "etsi_its_cam_coding/cam_PathHistory.h"
#include <etsi_its_cam_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* cam_BasicVehicleContainerLowFrequency */
typedef struct cam_BasicVehicleContainerLowFrequency {
	cam_VehicleRole_t	 vehicleRole;
	cam_ExteriorLights_t	 exteriorLights;
	cam_PathHistory_t	 pathHistory;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} cam_BasicVehicleContainerLowFrequency_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_cam_BasicVehicleContainerLowFrequency;
extern asn_SEQUENCE_specifics_t asn_SPC_cam_BasicVehicleContainerLowFrequency_specs_1;
extern asn_TYPE_member_t asn_MBR_cam_BasicVehicleContainerLowFrequency_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _cam_BasicVehicleContainerLowFrequency_H_ */
#include <etsi_its_cam_coding/asn_internal.h>
