/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=cam_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_cam_PositioningSolutionType_H_
#define	_cam_PositioningSolutionType_H_


#include <etsi_its_cam_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_cam_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum cam_PositioningSolutionType {
	cam_PositioningSolutionType_noPositioningSolution	= 0,
	cam_PositioningSolutionType_sGNSS	= 1,
	cam_PositioningSolutionType_dGNSS	= 2,
	cam_PositioningSolutionType_sGNSSplusDR	= 3,
	cam_PositioningSolutionType_dGNSSplusDR	= 4,
	cam_PositioningSolutionType_dR	= 5
	/*
	 * Enumeration is extensible
	 */
} e_cam_PositioningSolutionType;

/* cam_PositioningSolutionType */
typedef long	 cam_PositioningSolutionType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_cam_PositioningSolutionType;
asn_struct_free_f cam_PositioningSolutionType_free;
asn_struct_print_f cam_PositioningSolutionType_print;
asn_constr_check_f cam_PositioningSolutionType_constraint;
jer_type_encoder_f cam_PositioningSolutionType_encode_jer;
per_type_decoder_f cam_PositioningSolutionType_decode_uper;
per_type_encoder_f cam_PositioningSolutionType_encode_uper;
per_type_decoder_f cam_PositioningSolutionType_decode_aper;
per_type_encoder_f cam_PositioningSolutionType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _cam_PositioningSolutionType_H_ */
#include <etsi_its_cam_coding/asn_internal.h>
