/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=cam_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_cam_ts_VehicleRole_H_
#define	_cam_ts_VehicleRole_H_


#include <etsi_its_cam_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_cam_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum cam_ts_VehicleRole {
	cam_ts_VehicleRole_default	= 0,
	cam_ts_VehicleRole_publicTransport	= 1,
	cam_ts_VehicleRole_specialTransport	= 2,
	cam_ts_VehicleRole_dangerousGoods	= 3,
	cam_ts_VehicleRole_roadWork	= 4,
	cam_ts_VehicleRole_rescue	= 5,
	cam_ts_VehicleRole_emergency	= 6,
	cam_ts_VehicleRole_safetyCar	= 7,
	cam_ts_VehicleRole_agriculture	= 8,
	cam_ts_VehicleRole_commercial	= 9,
	cam_ts_VehicleRole_military	= 10,
	cam_ts_VehicleRole_roadOperator	= 11,
	cam_ts_VehicleRole_taxi	= 12,
	cam_ts_VehicleRole_uvar	= 13,
	cam_ts_VehicleRole_rfu1	= 14,
	cam_ts_VehicleRole_rfu2	= 15
} e_cam_ts_VehicleRole;

/* cam_ts_VehicleRole */
typedef long	 cam_ts_VehicleRole_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_cam_ts_VehicleRole_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_cam_ts_VehicleRole;
extern const asn_INTEGER_specifics_t asn_SPC_cam_ts_VehicleRole_specs_1;
asn_struct_free_f cam_ts_VehicleRole_free;
asn_struct_print_f cam_ts_VehicleRole_print;
asn_constr_check_f cam_ts_VehicleRole_constraint;
per_type_decoder_f cam_ts_VehicleRole_decode_uper;
per_type_encoder_f cam_ts_VehicleRole_encode_uper;
per_type_decoder_f cam_ts_VehicleRole_decode_aper;
per_type_encoder_f cam_ts_VehicleRole_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _cam_ts_VehicleRole_H_ */
#include <etsi_its_cam_ts_coding/asn_internal.h>
