/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=cam_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_cam_ts_MatrixIncludedComponents_H_
#define	_cam_ts_MatrixIncludedComponents_H_


#include <etsi_its_cam_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_cam_ts_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum cam_ts_MatrixIncludedComponents {
	cam_ts_MatrixIncludedComponents_xPosition	= 0,
	cam_ts_MatrixIncludedComponents_yPosition	= 1,
	cam_ts_MatrixIncludedComponents_zPosition	= 2,
	cam_ts_MatrixIncludedComponents_xVelocityOrVelocityMagnitude	= 3,
	cam_ts_MatrixIncludedComponents_yVelocityOrVelocityDirection	= 4,
	cam_ts_MatrixIncludedComponents_zSpeed	= 5,
	cam_ts_MatrixIncludedComponents_xAccelOrAccelMagnitude	= 6,
	cam_ts_MatrixIncludedComponents_yAccelOrAccelDirection	= 7,
	cam_ts_MatrixIncludedComponents_zAcceleration	= 8,
	cam_ts_MatrixIncludedComponents_zAngle	= 9,
	cam_ts_MatrixIncludedComponents_yAngle	= 10,
	cam_ts_MatrixIncludedComponents_xAngle	= 11,
	cam_ts_MatrixIncludedComponents_zAngularVelocity	= 12
} e_cam_ts_MatrixIncludedComponents;

/* cam_ts_MatrixIncludedComponents */
typedef BIT_STRING_t	 cam_ts_MatrixIncludedComponents_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_cam_ts_MatrixIncludedComponents_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_cam_ts_MatrixIncludedComponents;
asn_struct_free_f cam_ts_MatrixIncludedComponents_free;
asn_struct_print_f cam_ts_MatrixIncludedComponents_print;
asn_constr_check_f cam_ts_MatrixIncludedComponents_constraint;
per_type_decoder_f cam_ts_MatrixIncludedComponents_decode_uper;
per_type_encoder_f cam_ts_MatrixIncludedComponents_encode_uper;
per_type_decoder_f cam_ts_MatrixIncludedComponents_decode_aper;
per_type_encoder_f cam_ts_MatrixIncludedComponents_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _cam_ts_MatrixIncludedComponents_H_ */
#include <etsi_its_cam_ts_coding/asn_internal.h>
