# ------------------------------------------------------------------------------
# TisTpgTRM ::= SEQUENCE {
#  management TisTpgTRM-Management,
#  situation TisTpgTRM-Situation OPTIONAL,
#  location TisTpgTRM-Location OPTIONAL,
#  ...
# }
# ------------------------------------------------------------------------------

TisTpgTRM_Management management

# optional: True
TisTpgTRM_Situation situation

# optional: True
TisTpgTRM_Location location
