# ------------------------------------------------------------------------------
# TisTpgTCM ::= SEQUENCE {
#  management TisTpgTCM-Management,
#  situation TisTpgTCM-Situation OPTIONAL, 
#  location TisTpgTCM-Location OPTIONAL,
#  ...
# }
# ------------------------------------------------------------------------------

TisTpgTCM_Management management

# optional: True
TisTpgTCM_Situation situation

# optional: True
TisTpgTCM_Location location
