# ------------------------------------------------------------------------------
# TisTpgVDPM ::= SEQUENCE {
#  management TisTpgVDPM-Management,
#  placardTable PlacardTable,
#  vehicleSpecificData VehicleSpecificData OPTIONAL,
#  ...
# }
# ------------------------------------------------------------------------------

TisTpgVDPM_Management management

PlacardTable placardTable

# optional: True
VehicleSpecificData vehicleSpecificData
