StationID tpgStationID

TpgAutomation tpgAutomationLevel

TpgNumber tpgNumber

TpgProvider tpgProvider

ReferencePosition tpgLocation

Accessibility accessibility

# size: [(1, 128)]
# optional: True
string address

# optional: True
PhoneNumber phoneNumber

# optional: True
DigitalMap digitalMap

# optional: True
OpeningDaysHours openingDaysHours

# optional: True
BookingInfo bookingInfo

# optional: True
AvailableTpgNumber availableTpgNumber

# optional: True
CancellationCondition cancellationCondition

