# ------------------------------------------------------------------------------
# UNVehicleClassifcation ::= INTEGER {reserved(0), categoryL1(1), categoryL2(2), categoryL3(3), categoryL4(4), categoryL5(5), categoryL6(6), categoryL7(7), categoryL8(8)} (0..63)
# ------------------------------------------------------------------------------

# restricted-to: [(0, 63)]
uint8 RESERVED = 0
uint8 CATEGORY_L_1 = 1
uint8 CATEGORY_L_2 = 2
uint8 CATEGORY_L_3 = 3
uint8 CATEGORY_L_4 = 4
uint8 CATEGORY_L_5 = 5
uint8 CATEGORY_L_6 = 6
uint8 CATEGORY_L_7 = 7
uint8 CATEGORY_L_8 = 8
uint8 value
