# ------------------------------------------------------------------------------
# VehicleSpecificData ::= SEQUENCE {
#  currentVehicleConfiguration PressureConfiguration,
#  frontLeftTyreData TyreData,
#  frontRightTyreData TyreData,
#  rearLeftTyreData TyreData,
#  rearRightTyreData TyreData,
#  spareTyreData TyreData,
#  ...
# }
# ------------------------------------------------------------------------------

PressureConfiguration currentVehicleConfiguration

TyreData frontLeftTyreData

TyreData frontRightTyreData

TyreData rearLeftTyreData

TyreData rearRightTyreData

TyreData spareTyreData
