/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fcompound-names -no-gen-example -gen-UPER`
 */


/* Including external dependencies */
#include <etsi_its_mapem_ts_coding/IA5String.h>
#ifndef	_DescriptiveName_H_
#define	_DescriptiveName_H_


#include <etsi_its_mapem_ts_coding/asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DescriptiveName */
typedef IA5String_t	 DescriptiveName_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DescriptiveName_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DescriptiveName;
asn_struct_free_f DescriptiveName_free;
asn_struct_print_f DescriptiveName_print;
asn_constr_check_f DescriptiveName_constraint;
ber_type_decoder_f DescriptiveName_decode_ber;
der_type_encoder_f DescriptiveName_encode_der;
xer_type_decoder_f DescriptiveName_decode_xer;
xer_type_encoder_f DescriptiveName_encode_xer;
jer_type_encoder_f DescriptiveName_encode_jer;
oer_type_decoder_f DescriptiveName_decode_oer;
oer_type_encoder_f DescriptiveName_encode_oer;
per_type_decoder_f DescriptiveName_decode_uper;
per_type_encoder_f DescriptiveName_encode_uper;
per_type_decoder_f DescriptiveName_decode_aper;
per_type_encoder_f DescriptiveName_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _DescriptiveName_H_ */
#include <etsi_its_mapem_ts_coding/asn_internal.h>
