/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=mapem_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_mapem_ts_EmergencyVehicleApproachingSubCauseCode_H_
#define	_mapem_ts_EmergencyVehicleApproachingSubCauseCode_H_


#include <etsi_its_mapem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mapem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mapem_ts_EmergencyVehicleApproachingSubCauseCode {
	mapem_ts_EmergencyVehicleApproachingSubCauseCode_unavailable	= 0,
	mapem_ts_EmergencyVehicleApproachingSubCauseCode_emergencyVehicleApproaching	= 1,
	mapem_ts_EmergencyVehicleApproachingSubCauseCode_prioritizedVehicleApproaching	= 2
} e_mapem_ts_EmergencyVehicleApproachingSubCauseCode;

/* mapem_ts_EmergencyVehicleApproachingSubCauseCode */
typedef long	 mapem_ts_EmergencyVehicleApproachingSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mapem_ts_EmergencyVehicleApproachingSubCauseCode;
asn_struct_free_f mapem_ts_EmergencyVehicleApproachingSubCauseCode_free;
asn_struct_print_f mapem_ts_EmergencyVehicleApproachingSubCauseCode_print;
asn_constr_check_f mapem_ts_EmergencyVehicleApproachingSubCauseCode_constraint;
per_type_decoder_f mapem_ts_EmergencyVehicleApproachingSubCauseCode_decode_uper;
per_type_encoder_f mapem_ts_EmergencyVehicleApproachingSubCauseCode_encode_uper;
per_type_decoder_f mapem_ts_EmergencyVehicleApproachingSubCauseCode_decode_aper;
per_type_encoder_f mapem_ts_EmergencyVehicleApproachingSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mapem_ts_EmergencyVehicleApproachingSubCauseCode_H_ */
#include <etsi_its_mapem_ts_coding/asn_internal.h>
