/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=mapem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mapem_ts_ClosedLanes_H_
#define	_mapem_ts_ClosedLanes_H_


#include <etsi_its_mapem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mapem_ts_coding/mapem_ts_HardShoulderStatus.h"
#include "etsi_its_mapem_ts_coding/mapem_ts_DrivingLaneStatus.h"
#include <etsi_its_mapem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mapem_ts_ClosedLanes */
typedef struct mapem_ts_ClosedLanes {
	mapem_ts_HardShoulderStatus_t	*innerhardShoulderStatus;	/* OPTIONAL */
	mapem_ts_HardShoulderStatus_t	*outerhardShoulderStatus;	/* OPTIONAL */
	mapem_ts_DrivingLaneStatus_t	*drivingLaneStatus;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mapem_ts_ClosedLanes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mapem_ts_ClosedLanes;

#ifdef __cplusplus
}
#endif

#endif	/* _mapem_ts_ClosedLanes_H_ */
#include <etsi_its_mapem_ts_coding/asn_internal.h>
