/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=mapem_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_mapem_ts_LateralAcceleration_H_
#define	_mapem_ts_LateralAcceleration_H_


#include <etsi_its_mapem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mapem_ts_coding/mapem_ts_LateralAccelerationValue.h"
#include "etsi_its_mapem_ts_coding/mapem_ts_AccelerationConfidence.h"
#include <etsi_its_mapem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mapem_ts_LateralAcceleration */
typedef struct mapem_ts_LateralAcceleration {
	mapem_ts_LateralAccelerationValue_t	 lateralAccelerationValue;
	mapem_ts_AccelerationConfidence_t	 lateralAccelerationConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mapem_ts_LateralAcceleration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mapem_ts_LateralAcceleration;

#ifdef __cplusplus
}
#endif

#endif	/* _mapem_ts_LateralAcceleration_H_ */
#include <etsi_its_mapem_ts_coding/asn_internal.h>
