/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=mapem_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_mapem_ts_LaneAttributes_Barrier_H_
#define	_mapem_ts_LaneAttributes_Barrier_H_


#include <etsi_its_mapem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mapem_ts_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mapem_ts_LaneAttributes_Barrier {
	mapem_ts_LaneAttributes_Barrier_median_RevocableLane	= 0,
	mapem_ts_LaneAttributes_Barrier_median	= 1,
	mapem_ts_LaneAttributes_Barrier_whiteLineHashing	= 2,
	mapem_ts_LaneAttributes_Barrier_stripedLines	= 3,
	mapem_ts_LaneAttributes_Barrier_doubleStripedLines	= 4,
	mapem_ts_LaneAttributes_Barrier_trafficCones	= 5,
	mapem_ts_LaneAttributes_Barrier_constructionBarrier	= 6,
	mapem_ts_LaneAttributes_Barrier_trafficChannels	= 7,
	mapem_ts_LaneAttributes_Barrier_lowCurbs	= 8,
	mapem_ts_LaneAttributes_Barrier_highCurbs	= 9
} e_mapem_ts_LaneAttributes_Barrier;

/* mapem_ts_LaneAttributes-Barrier */
typedef BIT_STRING_t	 mapem_ts_LaneAttributes_Barrier_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mapem_ts_LaneAttributes_Barrier_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mapem_ts_LaneAttributes_Barrier;
asn_struct_free_f mapem_ts_LaneAttributes_Barrier_free;
asn_struct_print_f mapem_ts_LaneAttributes_Barrier_print;
asn_constr_check_f mapem_ts_LaneAttributes_Barrier_constraint;
per_type_decoder_f mapem_ts_LaneAttributes_Barrier_decode_uper;
per_type_encoder_f mapem_ts_LaneAttributes_Barrier_encode_uper;
per_type_decoder_f mapem_ts_LaneAttributes_Barrier_decode_aper;
per_type_encoder_f mapem_ts_LaneAttributes_Barrier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mapem_ts_LaneAttributes_Barrier_H_ */
#include <etsi_its_mapem_ts_coding/asn_internal.h>
