# ------------------------------------------------------------------------------
# PosConfidenceEllipse ::= SEQUENCE {
# 	semiMajorConfidence SemiAxisLength,
# 	semiMinorConfidence SemiAxisLength,
# 	semiMajorOrientation HeadingValue
# }
# ------------------------------------------------------------------------------

SemiAxisLength semiMajorConfidence

SemiAxisLength semiMinorConfidence

HeadingValue semiMajorOrientation
