# ------------------------------------------------------------------------------
# LaneAttributes-Sidewalk ::= BIT STRING { 
#   sidewalk-RevocableLane  (0),
#   bicyleUseAllowed        (1),
#   isSidewalkFlyOverLane   (2),
#   walkBikes               (3)
# } (SIZE (16))
# ------------------------------------------------------------------------------

# named-bits: [('sidewalk-RevocableLane', '0'), ('bicyleUseAllowed', '1'), ('isSidewalkFlyOverLane', '2'), ('walkBikes', '3')]
# size: [16]
string value
