# ------------------------------------------------------------------------------
# TransitVehicleOccupancy ::= ENUMERATED {
#   occupancyUnknown    (0),  
#   occupancyEmpty      (1),  
#   occupancyVeryLow    (2),  
#   occupancyLow        (3),  
#   occupancyMed        (4),  
#   occupancyHigh       (5),  
#   occupancyNearlyFull (6),  
#   occupancyFull       (7)
# }
# ------------------------------------------------------------------------------

uint8 OCCUPANCY_UNKNOWN = 0
uint8 OCCUPANCY_EMPTY = 1
uint8 OCCUPANCY_VERY_LOW = 2
uint8 OCCUPANCY_LOW = 3
uint8 OCCUPANCY_MED = 4
uint8 OCCUPANCY_HIGH = 5
uint8 OCCUPANCY_NEARLY_FULL = 6
uint8 OCCUPANCY_FULL = 7
uint8 value
