# ------------------------------------------------------------------------------
# EVChargingSpotNotificationPOIMessage ::= SEQUENCE {
# 	poiHeader	ItsPOIHeader, -- Specific POI Message Header
# 	evcsnData	ItsEVCSNData  -- Electric Vehicle Charging Spot Data Elements
# }
# ------------------------------------------------------------------------------

ItsPOIHeader poiHeader

ItsEVCSNData evcsnData
