StationID chargingStationID

# size: [(1, 32)]
# optional: True
string utilityDistributorId

# size: [(1, 32)]
# optional: True
string providerID

ReferencePosition chargingStationLocation

# optional: True
string address

# size: [(1, 16)]
# optional: True
string phoneNumber

# size: [(1, 32)]
string accessibility

# optional: True
DigitalMap digitalMap

string openingDaysHours

string pricing

# optional: True
string bookingContactInfo

# optional: True
string payment

ItsChargingSpots chargingSpotsAvailable

