// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/denm_ts103831/DENM-PDU-Descriptions.asn \
  asn1/patched/denm_ts103831/cdd/ETSI-ITS-CDD.asn \
  -t \
  denm_ts \
  -o \
  etsi_its_conversion/etsi_its_denm_ts_conversion/include/etsi_its_denm_ts_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
*
 * This DF represents a velocity vector in a cartesian coordinate system.
 
 * It shall include the following components: 
 * 
 * @field xVelocity: the x component of the velocity vector with the associated confidence value.
 * 
 * @field yVelocity: the y component of the velocity vector with the associated confidence value.
 *
 * @field zVelocity: the optional z component of the velocity vector with the associated confidence value.
 * 
 * @category: Kinematic information
 * @revision: Created in V2.1.1
 *
VelocityCartesian::= SEQUENCE {
    xVelocity   VelocityComponent,
    yVelocity   VelocityComponent,
    zVelocity   VelocityComponent OPTIONAL
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_denm_ts_coding/denm_ts_VelocityCartesian.h>
#include <etsi_its_denm_ts_conversion/convertVelocityComponent.h>
#include <etsi_its_denm_ts_msgs/msg/velocity_cartesian.hpp>
namespace denm_ts_msgs = etsi_its_denm_ts_msgs::msg;


namespace etsi_its_denm_ts_conversion {

void toRos_VelocityCartesian(const denm_ts_VelocityCartesian_t& in, denm_ts_msgs::VelocityCartesian& out) {
  toRos_VelocityComponent(in.xVelocity, out.x_velocity);
  toRos_VelocityComponent(in.yVelocity, out.y_velocity);
  if (in.zVelocity) {
    toRos_VelocityComponent(*in.zVelocity, out.z_velocity);
    out.z_velocity_is_present = true;
  }
}

void toStruct_VelocityCartesian(const denm_ts_msgs::VelocityCartesian& in, denm_ts_VelocityCartesian_t& out) {
  memset(&out, 0, sizeof(denm_ts_VelocityCartesian_t));
  toStruct_VelocityComponent(in.x_velocity, out.xVelocity);
  toStruct_VelocityComponent(in.y_velocity, out.yVelocity);
  if (in.z_velocity_is_present) {
    out.zVelocity = (denm_ts_VelocityComponent_t*) calloc(1, sizeof(denm_ts_VelocityComponent_t));
    toStruct_VelocityComponent(in.z_velocity, *out.zVelocity);
  }
}

}
