ActionID actionID

TimestampIts detectionTime

TimestampIts referenceTime

# optional: True
Termination termination

ReferencePosition eventPosition

# optional: True
RelevanceDistance relevanceDistance

# optional: True
RelevanceTrafficDirection relevanceTrafficDirection

# default: defaultValidity
ValidityDuration validityDuration

# optional: True
TransmissionInterval transmissionInterval

StationType stationType

