# ------------------------------------------------------------------------------
# PositionConfidence ::= ENUMERATED {
#    unavailable (0),
#    a500m   (1),
#    a200m   (2),
#    a100m   (3),
#    a50m    (4),
#    a20m    (5),
#    a10m    (6),
#    a5m     (7),
#    a2m     (8),
#    a1m     (9),
#    a50cm  (10),
#    a20cm  (11),
#    a10cm  (12),
#    a5cm   (13),
#    a2cm   (14),
#    a1cm   (15)
#    } 
# ------------------------------------------------------------------------------

uint8 UNAVAILABLE = 0
uint8 A_5_0_0M = 1
uint8 A_2_0_0M = 2
uint8 A_1_0_0M = 3
uint8 A_5_0M = 4
uint8 A_2_0M = 5
uint8 A_1_0M = 6
uint8 A_5M = 7
uint8 A_2M = 8
uint8 A_1M = 9
uint8 A_5_0CM = 10
uint8 A_2_0CM = 11
uint8 A_1_0CM = 12
uint8 A_5CM = 13
uint8 A_2CM = 14
uint8 A_1CM = 15
uint8 value
