## SEQUENCE ManagementContainer .extensible

ActionID action_id


TimestampIts detection_time


TimestampIts reference_time


bool termination_is_present
Termination termination


ReferencePosition event_position


bool relevance_distance_is_present
RelevanceDistance relevance_distance


bool relevance_traffic_direction_is_present
RelevanceTrafficDirection relevance_traffic_direction


ValidityDuration validity_duration


bool transmission_interval_is_present
TransmissionInterval transmission_interval


StationType station_type





uint32 VALIDITY_DURATION_DEFAULT = 600

