/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "/input/VAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=vam_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#include "etsi_its_vam_ts_coding/vam_ts_ItsPduHeaderVam.h"

int
vam_ts_ItsPduHeaderVam_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	/* prevent infinite recursion */
	if(td->encoding_constraints.general_constraints != vam_ts_ItsPduHeaderVam_constraint) {
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		return 0;
	}
}

/*
 * This type is implemented using vam_ts_ItsPduHeader,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_vam_ts_ItsPduHeaderVam_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const ber_tlv_tag_t asn_DEF_vam_ts_ItsPduHeaderVam_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_vam_ts_ItsPduHeaderVam = {
	"ItsPduHeaderVam",
	"ItsPduHeaderVam",
	&asn_OP_SEQUENCE,
	asn_DEF_vam_ts_ItsPduHeaderVam_tags_1,
	sizeof(asn_DEF_vam_ts_ItsPduHeaderVam_tags_1)
		/sizeof(asn_DEF_vam_ts_ItsPduHeaderVam_tags_1[0]), /* 1 */
	asn_DEF_vam_ts_ItsPduHeaderVam_tags_1,	/* Same as above */
	sizeof(asn_DEF_vam_ts_ItsPduHeaderVam_tags_1)
		/sizeof(asn_DEF_vam_ts_ItsPduHeaderVam_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_vam_ts_ItsPduHeaderVam_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		vam_ts_ItsPduHeaderVam_constraint
	},
	asn_MBR_vam_ts_ItsPduHeader_1,
	3,	/* Elements count */
	&asn_SPC_vam_ts_ItsPduHeader_specs_1	/* Additional specs */
};

