// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/is_ts103301/MAPEM-PDU-Descriptions.asn \
  asn1/raw/is_ts103301/cdd/ITS-Container.asn \
  asn1/raw/is_ts103301/iso-patched/ISO24534-3_ElectronicRegistrationIdentificationVehicleDataModule-patched.asn \
  asn1/raw/is_ts103301/build/asn1/ISO-TS-19091-addgrp-C-2018-patched.asn \
  asn1/patched/is_ts103301/build/asn1/ISO14816_AVIAEINumberingAndDataStructures.asn \
  -t \
  mapem_ts \
  -o \
  etsi_its_conversion/etsi_its_mapem_ts_conversion/include/etsi_its_mapem_ts_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
IntersectionGeometry ::= SEQUENCE {
  name        DescriptiveName OPTIONAL, 
  id          IntersectionReferenceID,  
  revision    MsgCount,    
  refPoint    Position3D,
  laneWidth   LaneWidth OPTIONAL,   
  speedLimits SpeedLimitList OPTIONAL, 
  laneSet     LaneList,
  preemptPriorityData PreemptPriorityList OPTIONAL, 
  regional     SEQUENCE (SIZE(1..4)) OF 
               RegionalExtension {{Reg-IntersectionGeometry}} OPTIONAL,
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_mapem_ts_coding/mapem_ts_IntersectionGeometry.h>
#include <etsi_its_mapem_ts_conversion/convertDescriptiveName.h>
#include <etsi_its_mapem_ts_conversion/convertIntersectionReferenceID.h>
#include <etsi_its_mapem_ts_conversion/convertLaneList.h>
#include <etsi_its_mapem_ts_conversion/convertLaneWidth.h>
#include <etsi_its_mapem_ts_conversion/convertMsgCount.h>
#include <etsi_its_mapem_ts_conversion/convertPosition3D.h>
#include <etsi_its_mapem_ts_conversion/convertPreemptPriorityList.h>
#include <etsi_its_mapem_ts_conversion/convertSpeedLimitList.h>
#include <etsi_its_mapem_ts_msgs/msg/intersection_geometry.hpp>
namespace mapem_ts_msgs = etsi_its_mapem_ts_msgs::msg;


namespace etsi_its_mapem_ts_conversion {

void toRos_IntersectionGeometry(const mapem_ts_IntersectionGeometry_t& in, mapem_ts_msgs::IntersectionGeometry& out) {
  if (in.name) {
    toRos_DescriptiveName(*in.name, out.name);
    out.name_is_present = true;
  }
  toRos_IntersectionReferenceID(in.id, out.id);
  toRos_MsgCount(in.revision, out.revision);
  toRos_Position3D(in.refPoint, out.ref_point);
  if (in.laneWidth) {
    toRos_LaneWidth(*in.laneWidth, out.lane_width);
    out.lane_width_is_present = true;
  }
  if (in.speedLimits) {
    toRos_SpeedLimitList(*in.speedLimits, out.speed_limits);
    out.speed_limits_is_present = true;
  }
  toRos_LaneList(in.laneSet, out.lane_set);
  if (in.preemptPriorityData) {
    toRos_PreemptPriorityList(*in.preemptPriorityData, out.preempt_priority_data);
    out.preempt_priority_data_is_present = true;
  }
}

void toStruct_IntersectionGeometry(const mapem_ts_msgs::IntersectionGeometry& in, mapem_ts_IntersectionGeometry_t& out) {
  memset(&out, 0, sizeof(mapem_ts_IntersectionGeometry_t));
  if (in.name_is_present) {
    out.name = (mapem_ts_DescriptiveName_t*) calloc(1, sizeof(mapem_ts_DescriptiveName_t));
    toStruct_DescriptiveName(in.name, *out.name);
  }
  toStruct_IntersectionReferenceID(in.id, out.id);
  toStruct_MsgCount(in.revision, out.revision);
  toStruct_Position3D(in.ref_point, out.refPoint);
  if (in.lane_width_is_present) {
    out.laneWidth = (mapem_ts_LaneWidth_t*) calloc(1, sizeof(mapem_ts_LaneWidth_t));
    toStruct_LaneWidth(in.lane_width, *out.laneWidth);
  }
  if (in.speed_limits_is_present) {
    out.speedLimits = (mapem_ts_SpeedLimitList_t*) calloc(1, sizeof(mapem_ts_SpeedLimitList_t));
    toStruct_SpeedLimitList(in.speed_limits, *out.speedLimits);
  }
  toStruct_LaneList(in.lane_set, out.laneSet);
  if (in.preempt_priority_data_is_present) {
    out.preemptPriorityData = (mapem_ts_PreemptPriorityList_t*) calloc(1, sizeof(mapem_ts_PreemptPriorityList_t));
    toStruct_PreemptPriorityList(in.preempt_priority_data, *out.preemptPriorityData);
  }
}

}
