// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/is_ts103301/MAPEM-PDU-Descriptions.asn \
  asn1/raw/is_ts103301/cdd/ITS-Container.asn \
  asn1/raw/is_ts103301/iso-patched/ISO24534-3_ElectronicRegistrationIdentificationVehicleDataModule-patched.asn \
  asn1/raw/is_ts103301/build/asn1/ISO-TS-19091-addgrp-C-2018-patched.asn \
  asn1/patched/is_ts103301/build/asn1/ISO14816_AVIAEINumberingAndDataStructures.asn \
  -t \
  mapem_ts \
  -o \
  etsi_its_conversion/etsi_its_mapem_ts_conversion/include/etsi_its_mapem_ts_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
RestrictionUserType ::= CHOICE {
  basicType   RestrictionAppliesTo,
  regional    SEQUENCE (SIZE(1..4)) OF 
              RegionalExtension {{Reg-RestrictionUserType}}, 
  ...
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_mapem_ts_coding/mapem_ts_RestrictionUserType.h>
#include <etsi_its_mapem_ts_conversion/convertRestrictionAppliesTo.h>
#include <etsi_its_mapem_ts_msgs/msg/restriction_user_type.hpp>
namespace mapem_ts_msgs = etsi_its_mapem_ts_msgs::msg;


namespace etsi_its_mapem_ts_conversion {

void toRos_RestrictionUserType(const mapem_ts_RestrictionUserType_t& in, mapem_ts_msgs::RestrictionUserType& out) {
  switch (in.present) {
  case mapem_ts_RestrictionUserType_PR_basicType:
    toRos_RestrictionAppliesTo(in.choice.basicType, out.basic_type);
    out.choice = mapem_ts_msgs::RestrictionUserType::CHOICE_BASIC_TYPE;
    break;
  default: break;
  }
}

void toStruct_RestrictionUserType(const mapem_ts_msgs::RestrictionUserType& in, mapem_ts_RestrictionUserType_t& out) {
  memset(&out, 0, sizeof(mapem_ts_RestrictionUserType_t));
  switch (in.choice) {
  case mapem_ts_msgs::RestrictionUserType::CHOICE_BASIC_TYPE:
    toStruct_RestrictionAppliesTo(in.basic_type, out.choice.basicType);
    out.present = mapem_ts_RestrictionUserType_PR::mapem_ts_RestrictionUserType_PR_basicType;
    break;
  default: break;
  }
}

}
