/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=rtcmem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_rtcmem_ts_CollisionRiskSubCauseCode_H_
#define	_rtcmem_ts_CollisionRiskSubCauseCode_H_


#include <etsi_its_rtcmem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_rtcmem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum rtcmem_ts_CollisionRiskSubCauseCode {
	rtcmem_ts_CollisionRiskSubCauseCode_unavailable	= 0,
	rtcmem_ts_CollisionRiskSubCauseCode_longitudinalCollisionRisk	= 1,
	rtcmem_ts_CollisionRiskSubCauseCode_crossingCollisionRisk	= 2,
	rtcmem_ts_CollisionRiskSubCauseCode_lateralCollisionRisk	= 3,
	rtcmem_ts_CollisionRiskSubCauseCode_vulnerableRoadUser	= 4
} e_rtcmem_ts_CollisionRiskSubCauseCode;

/* rtcmem_ts_CollisionRiskSubCauseCode */
typedef long	 rtcmem_ts_CollisionRiskSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_rtcmem_ts_CollisionRiskSubCauseCode;
asn_struct_free_f rtcmem_ts_CollisionRiskSubCauseCode_free;
asn_struct_print_f rtcmem_ts_CollisionRiskSubCauseCode_print;
asn_constr_check_f rtcmem_ts_CollisionRiskSubCauseCode_constraint;
jer_type_encoder_f rtcmem_ts_CollisionRiskSubCauseCode_encode_jer;
per_type_decoder_f rtcmem_ts_CollisionRiskSubCauseCode_decode_uper;
per_type_encoder_f rtcmem_ts_CollisionRiskSubCauseCode_encode_uper;
per_type_decoder_f rtcmem_ts_CollisionRiskSubCauseCode_decode_aper;
per_type_encoder_f rtcmem_ts_CollisionRiskSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _rtcmem_ts_CollisionRiskSubCauseCode_H_ */
#include <etsi_its_rtcmem_ts_coding/asn_internal.h>
