/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/input/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ivim_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_ivim_ts_SetMMIRq_H_
#define	_ivim_ts_SetMMIRq_H_


#include <etsi_its_ivim_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ivim_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ivim_ts_SetMMIRq {
	ivim_ts_SetMMIRq_ok	= 0,
	ivim_ts_SetMMIRq_nok	= 1,
	ivim_ts_SetMMIRq_contactOperator	= 2,
	ivim_ts_SetMMIRq_noSignalling	= 255
} e_ivim_ts_SetMMIRq;

/* ivim_ts_SetMMIRq */
typedef long	 ivim_ts_SetMMIRq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ivim_ts_SetMMIRq;
asn_struct_free_f ivim_ts_SetMMIRq_free;
asn_struct_print_f ivim_ts_SetMMIRq_print;
asn_constr_check_f ivim_ts_SetMMIRq_constraint;
per_type_decoder_f ivim_ts_SetMMIRq_decode_uper;
per_type_encoder_f ivim_ts_SetMMIRq_encode_uper;
per_type_decoder_f ivim_ts_SetMMIRq_decode_aper;
per_type_encoder_f ivim_ts_SetMMIRq_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ivim_ts_SetMMIRq_H_ */
#include <etsi_its_ivim_ts_coding/asn_internal.h>
