/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "/input/ISO19321IVIv2.asn"
 * 	`asn1c -fcompound-names -fprefix=ivim_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_ivim_ts_Zone_H_
#define	_ivim_ts_Zone_H_


#include <etsi_its_ivim_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ivim_ts_coding/ivim_ts_Segment.h"
#include "etsi_its_ivim_ts_coding/ivim_ts_PolygonalLine.h"
#include "etsi_its_ivim_ts_coding/ivim_ts_ComputedSegment.h"
#include <etsi_its_ivim_ts_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ivim_ts_Zone_PR {
	ivim_ts_Zone_PR_NOTHING,	/* No components present */
	ivim_ts_Zone_PR_segment,
	ivim_ts_Zone_PR_area,
	ivim_ts_Zone_PR_computedSegment
	/* Extensions may appear below */
	
} ivim_ts_Zone_PR;

/* ivim_ts_Zone */
typedef struct ivim_ts_Zone {
	ivim_ts_Zone_PR present;
	union ivim_ts_Zone_u {
		ivim_ts_Segment_t	 segment;
		ivim_ts_PolygonalLine_t	 area;
		ivim_ts_ComputedSegment_t	 computedSegment;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ivim_ts_Zone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ivim_ts_Zone;
extern asn_CHOICE_specifics_t asn_SPC_ivim_ts_Zone_specs_1;
extern asn_TYPE_member_t asn_MBR_ivim_ts_Zone_1[3];
extern asn_per_constraints_t asn_PER_type_ivim_ts_Zone_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ivim_ts_Zone_H_ */
#include <etsi_its_ivim_ts_coding/asn_internal.h>
