/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/input/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ivim_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_ivim_ts_ContractSerialNumber_H_
#define	_ivim_ts_ContractSerialNumber_H_


#include <etsi_its_ivim_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ivim_ts_coding/ivim_ts_Int4.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ivim_ts_ContractSerialNumber */
typedef ivim_ts_Int4_t	 ivim_ts_ContractSerialNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ivim_ts_ContractSerialNumber;
asn_struct_free_f ivim_ts_ContractSerialNumber_free;
asn_struct_print_f ivim_ts_ContractSerialNumber_print;
asn_constr_check_f ivim_ts_ContractSerialNumber_constraint;
per_type_decoder_f ivim_ts_ContractSerialNumber_decode_uper;
per_type_encoder_f ivim_ts_ContractSerialNumber_encode_uper;
per_type_decoder_f ivim_ts_ContractSerialNumber_decode_aper;
per_type_encoder_f ivim_ts_ContractSerialNumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ivim_ts_ContractSerialNumber_H_ */
#include <etsi_its_ivim_ts_coding/asn_internal.h>
