/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/input/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ivim_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_ivim_ts_CopValue_H_
#define	_ivim_ts_CopValue_H_


#include <etsi_its_ivim_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ivim_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ivim_ts_CopValue {
	ivim_ts_CopValue_noEntry	= 0,
	ivim_ts_CopValue_co2class1	= 1,
	ivim_ts_CopValue_co2class2	= 2,
	ivim_ts_CopValue_co2class3	= 3,
	ivim_ts_CopValue_co2class4	= 4,
	ivim_ts_CopValue_co2class5	= 5,
	ivim_ts_CopValue_co2class6	= 6,
	ivim_ts_CopValue_co2class7	= 7,
	ivim_ts_CopValue_reservedforUse	= 8
} e_ivim_ts_CopValue;

/* ivim_ts_CopValue */
typedef long	 ivim_ts_CopValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ivim_ts_CopValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ivim_ts_CopValue;
extern const asn_INTEGER_specifics_t asn_SPC_ivim_ts_CopValue_specs_1;
asn_struct_free_f ivim_ts_CopValue_free;
asn_struct_print_f ivim_ts_CopValue_print;
asn_constr_check_f ivim_ts_CopValue_constraint;
per_type_decoder_f ivim_ts_CopValue_decode_uper;
per_type_encoder_f ivim_ts_CopValue_encode_uper;
per_type_decoder_f ivim_ts_CopValue_decode_aper;
per_type_encoder_f ivim_ts_CopValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ivim_ts_CopValue_H_ */
#include <etsi_its_ivim_ts_coding/asn_internal.h>
