/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "/input/ISO19321IVIv2.asn"
 * 	`asn1c -fcompound-names -fprefix=ivim_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_ivim_ts_LaneMarkingStatus_H_
#define	_ivim_ts_LaneMarkingStatus_H_


#include <etsi_its_ivim_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ivim_ts_coding/BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ivim_ts_LaneMarkingStatus */
typedef BOOLEAN_t	 ivim_ts_LaneMarkingStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ivim_ts_LaneMarkingStatus;
asn_struct_free_f ivim_ts_LaneMarkingStatus_free;
asn_struct_print_f ivim_ts_LaneMarkingStatus_print;
asn_constr_check_f ivim_ts_LaneMarkingStatus_constraint;
per_type_decoder_f ivim_ts_LaneMarkingStatus_decode_uper;
per_type_encoder_f ivim_ts_LaneMarkingStatus_encode_uper;
per_type_decoder_f ivim_ts_LaneMarkingStatus_decode_aper;
per_type_encoder_f ivim_ts_LaneMarkingStatus_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ivim_ts_LaneMarkingStatus_H_ */
#include <etsi_its_ivim_ts_coding/asn_internal.h>
