/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "GDD"
 * 	found in "/input/ISO14823-missing.asn"
 * 	`asn1c -fcompound-names -fprefix=ivim_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_ivim_ts_DestinationPlace_H_
#define	_ivim_ts_DestinationPlace_H_


#include <etsi_its_ivim_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ivim_ts_coding/ivim_ts_DestinationType.h"
#include <etsi_its_ivim_ts_coding/OCTET_STRING.h>
#include <etsi_its_ivim_ts_coding/NativeInteger.h>
#include <etsi_its_ivim_ts_coding/UTF8String.h>
#include <etsi_its_ivim_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ivim_ts_GddStructure;

/* ivim_ts_DestinationPlace */
typedef struct ivim_ts_DestinationPlace {
	ivim_ts_DestinationType_t	 destType;
	struct ivim_ts_GddStructure	*destRSCode;	/* OPTIONAL */
	OCTET_STRING_t	*destBlob;	/* OPTIONAL */
	long	*placeNameIdentification;	/* OPTIONAL */
	UTF8String_t	*placeNameText;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ivim_ts_DestinationPlace_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ivim_ts_DestinationPlace;
extern asn_SEQUENCE_specifics_t asn_SPC_ivim_ts_DestinationPlace_specs_1;
extern asn_TYPE_member_t asn_MBR_ivim_ts_DestinationPlace_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_ivim_ts_coding/ivim_ts_GddStructure.h"

#endif	/* _ivim_ts_DestinationPlace_H_ */
#include <etsi_its_ivim_ts_coding/asn_internal.h>
