/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "/input/ISO19321IVIv2.asn"
 * 	`asn1c -fcompound-names -fprefix=ivim_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ivim_ts_VcOption_H_
#define	_ivim_ts_VcOption_H_


#include <etsi_its_ivim_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ivim_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ivim_ts_VcOption {
	ivim_ts_VcOption_none	= 0,
	ivim_ts_VcOption_a	= 1,
	ivim_ts_VcOption_b	= 2,
	ivim_ts_VcOption_c	= 3,
	ivim_ts_VcOption_d	= 4,
	ivim_ts_VcOption_e	= 5,
	ivim_ts_VcOption_f	= 6,
	ivim_ts_VcOption_g	= 7
} e_ivim_ts_VcOption;

/* ivim_ts_VcOption */
typedef long	 ivim_ts_VcOption_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ivim_ts_VcOption_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ivim_ts_VcOption;
asn_struct_free_f ivim_ts_VcOption_free;
asn_struct_print_f ivim_ts_VcOption_print;
asn_constr_check_f ivim_ts_VcOption_constraint;
jer_type_encoder_f ivim_ts_VcOption_encode_jer;
per_type_decoder_f ivim_ts_VcOption_decode_uper;
per_type_encoder_f ivim_ts_VcOption_encode_uper;
per_type_decoder_f ivim_ts_VcOption_decode_aper;
per_type_encoder_f ivim_ts_VcOption_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ivim_ts_VcOption_H_ */
#include <etsi_its_ivim_ts_coding/asn_internal.h>
