/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/input/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ivim_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_ivim_ts_UnitType_H_
#define	_ivim_ts_UnitType_H_


#include <etsi_its_ivim_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ivim_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ivim_ts_UnitType {
	ivim_ts_UnitType_mg_km	= 0,
	ivim_ts_UnitType_mg_kWh	= 1
} e_ivim_ts_UnitType;

/* ivim_ts_UnitType */
typedef long	 ivim_ts_UnitType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ivim_ts_UnitType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ivim_ts_UnitType;
extern const asn_INTEGER_specifics_t asn_SPC_ivim_ts_UnitType_specs_1;
asn_struct_free_f ivim_ts_UnitType_free;
asn_struct_print_f ivim_ts_UnitType_print;
asn_constr_check_f ivim_ts_UnitType_constraint;
per_type_decoder_f ivim_ts_UnitType_decode_uper;
per_type_encoder_f ivim_ts_UnitType_encode_uper;
per_type_decoder_f ivim_ts_UnitType_decode_aper;
per_type_encoder_f ivim_ts_UnitType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ivim_ts_UnitType_H_ */
#include <etsi_its_ivim_ts_coding/asn_internal.h>
