/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/input/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ivim_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_ivim_ts_ReceiptFinancialPart_H_
#define	_ivim_ts_ReceiptFinancialPart_H_


#include <etsi_its_ivim_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ivim_ts_coding/ivim_ts_PersonalAccountNumber.h"
#include "etsi_its_ivim_ts_coding/ivim_ts_PaymentFee.h"
#include "etsi_its_ivim_ts_coding/ivim_ts_PurseBalance.h"
#include "etsi_its_ivim_ts_coding/ivim_ts_Int4.h"
#include <etsi_its_ivim_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ivim_ts_ReceiptFinancialPart */
typedef struct ivim_ts_ReceiptFinancialPart {
	ivim_ts_PersonalAccountNumber_t	 personalAccountNumber;
	ivim_ts_PaymentFee_t	 sessionPaymentFee;
	ivim_ts_PurseBalance_t	 sessionCurrentBalance;
	ivim_ts_Int4_t	 receiptFinancialSerialNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ivim_ts_ReceiptFinancialPart_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ivim_ts_ReceiptFinancialPart;

#ifdef __cplusplus
}
#endif

#endif	/* _ivim_ts_ReceiptFinancialPart_H_ */
#include <etsi_its_ivim_ts_coding/asn_internal.h>
