# ------------------------------------------------------------------------------
# PowerSource::=  INTEGER { notApplicable(0), ac1Phase(1), ac2Phase(2), ac3Phase(3), dcc(4), chaDeMo(5) } (0..7)
# ------------------------------------------------------------------------------

# restricted-to: [(0, 7)]
uint8 NOT_APPLICABLE = 0
uint8 AC_1_PHASE = 1
uint8 AC_2_PHASE = 2
uint8 AC_3_PHASE = 3
uint8 DCC = 4
uint8 CHA_DE_MO = 5
uint8 value
