# ------------------------------------------------------------------------------
# UpdateRequestMessage ::= SEQUENCE {
#  reservation-ID				Reservation-ID,
#  reservation-Password		Reservation-Password,
#  updatedArrivalTime		TimestampUTC,
#  updatedDepartureTime		TimestampUTC,
#  ...
# }
# ------------------------------------------------------------------------------

Reservation_ID reservation_ID

Reservation_Password reservation_Password

TimestampUTC updatedArrivalTime

TimestampUTC updatedDepartureTime
