/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/TS103561_LUKAS_MCM.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_mcm_ts_MCM_H_
#define	_mcm_ts_MCM_H_


#include <uulm_mcm_ts_coding/asn_application.h>

/* Including external dependencies */
#include "uulm_mcm_ts_coding/mcm_ts_ItsPduHeader.h"
#include "uulm_mcm_ts_coding/mcm_ts_ManeuverCoordinationMessage.h"
#include <uulm_mcm_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* mcm_ts_MCM */
typedef struct mcm_ts_MCM {
	mcm_ts_ItsPduHeader_t	 header;
	mcm_ts_ManeuverCoordinationMessage_t	 mcm;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_ts_MCM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_ts_MCM;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_ts_MCM_H_ */
#include <uulm_mcm_ts_coding/asn_internal.h>
