/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_mcm_ts_ImpassabilitySubCauseCode_H_
#define	_mcm_ts_ImpassabilitySubCauseCode_H_


#include <uulm_mcm_ts_coding/asn_application.h>

/* Including external dependencies */
#include <uulm_mcm_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_ts_ImpassabilitySubCauseCode {
	mcm_ts_ImpassabilitySubCauseCode_unavailable	= 0,
	mcm_ts_ImpassabilitySubCauseCode_flooding	= 1,
	mcm_ts_ImpassabilitySubCauseCode_dangerOfAvalanches	= 2,
	mcm_ts_ImpassabilitySubCauseCode_blastingOfAvalanches	= 3,
	mcm_ts_ImpassabilitySubCauseCode_landslips	= 4,
	mcm_ts_ImpassabilitySubCauseCode_chemicalSpillage	= 5,
	mcm_ts_ImpassabilitySubCauseCode_winterClosure	= 6,
	mcm_ts_ImpassabilitySubCauseCode_sinkhole	= 7,
	mcm_ts_ImpassabilitySubCauseCode_earthquakeDamage	= 8,
	mcm_ts_ImpassabilitySubCauseCode_fallenTrees	= 9,
	mcm_ts_ImpassabilitySubCauseCode_rockfalls	= 10,
	mcm_ts_ImpassabilitySubCauseCode_sewerOverflow	= 11,
	mcm_ts_ImpassabilitySubCauseCode_stormDamage	= 12,
	mcm_ts_ImpassabilitySubCauseCode_subsidence	= 13,
	mcm_ts_ImpassabilitySubCauseCode_burstPipe	= 14,
	mcm_ts_ImpassabilitySubCauseCode_burstWaterMain	= 15,
	mcm_ts_ImpassabilitySubCauseCode_fallenPowerCables	= 16,
	mcm_ts_ImpassabilitySubCauseCode_snowDrifts	= 17
} e_mcm_ts_ImpassabilitySubCauseCode;

/* mcm_ts_ImpassabilitySubCauseCode */
typedef long	 mcm_ts_ImpassabilitySubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_ts_ImpassabilitySubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_ts_ImpassabilitySubCauseCode;
asn_struct_free_f mcm_ts_ImpassabilitySubCauseCode_free;
asn_struct_print_f mcm_ts_ImpassabilitySubCauseCode_print;
asn_constr_check_f mcm_ts_ImpassabilitySubCauseCode_constraint;
per_type_decoder_f mcm_ts_ImpassabilitySubCauseCode_decode_uper;
per_type_encoder_f mcm_ts_ImpassabilitySubCauseCode_encode_uper;
per_type_decoder_f mcm_ts_ImpassabilitySubCauseCode_decode_aper;
per_type_encoder_f mcm_ts_ImpassabilitySubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_ts_ImpassabilitySubCauseCode_H_ */
#include <uulm_mcm_ts_coding/asn_internal.h>
