// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/denm_en302637_3/DENM-PDU-Descriptions.asn \
  asn1/raw/denm_en302637_3/cdd/ITS-Container.asn \
  -t \
  denm \
  -o \
  etsi_its_conversion/etsi_its_denm_conversion/include/etsi_its_denm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
InformationQuality ::= INTEGER {unavailable(0), lowest(1), highest(7)} (0..7)
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_denm_coding/denm_InformationQuality.h>
#include <etsi_its_denm_coding/INTEGER.h>
#include <etsi_its_primitives_conversion/convertINTEGER.h>
#include <etsi_its_denm_msgs/msg/information_quality.hpp>
namespace denm_msgs = etsi_its_denm_msgs::msg;


namespace etsi_its_denm_conversion {

void toRos_InformationQuality(const denm_InformationQuality_t& in, denm_msgs::InformationQuality& out) {
  etsi_its_primitives_conversion::toRos_INTEGER(in, out.value);
}

void toStruct_InformationQuality(const denm_msgs::InformationQuality& in, denm_InformationQuality_t& out) {
  memset(&out, 0, sizeof(denm_InformationQuality_t));
  etsi_its_primitives_conversion::toStruct_INTEGER(in.value, out);
}

}
