// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/denm_en302637_3/DENM-PDU-Descriptions.asn \
  asn1/raw/denm_en302637_3/cdd/ITS-Container.asn \
  -t \
  denm \
  -o \
  etsi_its_conversion/etsi_its_denm_conversion/include/etsi_its_denm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
RequestResponseIndication ::= ENUMERATED {request(0), response(1)}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_denm_coding/denm_RequestResponseIndication.h>

#include <etsi_its_denm_msgs/msg/request_response_indication.hpp>
namespace denm_msgs = etsi_its_denm_msgs::msg;


namespace etsi_its_denm_conversion {

void toRos_RequestResponseIndication(const denm_RequestResponseIndication_t& in, denm_msgs::RequestResponseIndication& out) {
  out.value = in;
}

void toStruct_RequestResponseIndication(const denm_msgs::RequestResponseIndication& in, denm_RequestResponseIndication_t& out) {
  memset(&out, 0, sizeof(denm_RequestResponseIndication_t));
  out = in.value;
}

}
