// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/denm_en302637_3/DENM-PDU-Descriptions.asn \
  asn1/raw/denm_en302637_3/cdd/ITS-Container.asn \
  -t \
  denm \
  -o \
  etsi_its_conversion/etsi_its_denm_conversion/include/etsi_its_denm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
ImpactReductionContainer ::= SEQUENCE {
	heightLonCarrLeft HeightLonCarr,
	heightLonCarrRight HeightLonCarr,
	posLonCarrLeft PosLonCarr,
	posLonCarrRight PosLonCarr,
	positionOfPillars PositionOfPillars,
	posCentMass PosCentMass,
	wheelBaseVehicle WheelBaseVehicle,
	turningRadius TurningRadius,
	posFrontAx PosFrontAx,
	positionOfOccupants PositionOfOccupants,
	vehicleMass VehicleMass,
	requestResponseIndication RequestResponseIndication
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_denm_coding/denm_ImpactReductionContainer.h>
#include <etsi_its_denm_conversion/convertHeightLonCarr.h>
#include <etsi_its_denm_conversion/convertPosCentMass.h>
#include <etsi_its_denm_conversion/convertPosFrontAx.h>
#include <etsi_its_denm_conversion/convertPosLonCarr.h>
#include <etsi_its_denm_conversion/convertPositionOfOccupants.h>
#include <etsi_its_denm_conversion/convertPositionOfPillars.h>
#include <etsi_its_denm_conversion/convertRequestResponseIndication.h>
#include <etsi_its_denm_conversion/convertTurningRadius.h>
#include <etsi_its_denm_conversion/convertVehicleMass.h>
#include <etsi_its_denm_conversion/convertWheelBaseVehicle.h>
#include <etsi_its_denm_msgs/msg/impact_reduction_container.hpp>
namespace denm_msgs = etsi_its_denm_msgs::msg;


namespace etsi_its_denm_conversion {

void toRos_ImpactReductionContainer(const denm_ImpactReductionContainer_t& in, denm_msgs::ImpactReductionContainer& out) {
  toRos_HeightLonCarr(in.heightLonCarrLeft, out.height_lon_carr_left);
  toRos_HeightLonCarr(in.heightLonCarrRight, out.height_lon_carr_right);
  toRos_PosLonCarr(in.posLonCarrLeft, out.pos_lon_carr_left);
  toRos_PosLonCarr(in.posLonCarrRight, out.pos_lon_carr_right);
  toRos_PositionOfPillars(in.positionOfPillars, out.position_of_pillars);
  toRos_PosCentMass(in.posCentMass, out.pos_cent_mass);
  toRos_WheelBaseVehicle(in.wheelBaseVehicle, out.wheel_base_vehicle);
  toRos_TurningRadius(in.turningRadius, out.turning_radius);
  toRos_PosFrontAx(in.posFrontAx, out.pos_front_ax);
  toRos_PositionOfOccupants(in.positionOfOccupants, out.position_of_occupants);
  toRos_VehicleMass(in.vehicleMass, out.vehicle_mass);
  toRos_RequestResponseIndication(in.requestResponseIndication, out.request_response_indication);
}

void toStruct_ImpactReductionContainer(const denm_msgs::ImpactReductionContainer& in, denm_ImpactReductionContainer_t& out) {
  memset(&out, 0, sizeof(denm_ImpactReductionContainer_t));
  toStruct_HeightLonCarr(in.height_lon_carr_left, out.heightLonCarrLeft);
  toStruct_HeightLonCarr(in.height_lon_carr_right, out.heightLonCarrRight);
  toStruct_PosLonCarr(in.pos_lon_carr_left, out.posLonCarrLeft);
  toStruct_PosLonCarr(in.pos_lon_carr_right, out.posLonCarrRight);
  toStruct_PositionOfPillars(in.position_of_pillars, out.positionOfPillars);
  toStruct_PosCentMass(in.pos_cent_mass, out.posCentMass);
  toStruct_WheelBaseVehicle(in.wheel_base_vehicle, out.wheelBaseVehicle);
  toStruct_TurningRadius(in.turning_radius, out.turningRadius);
  toStruct_PosFrontAx(in.pos_front_ax, out.posFrontAx);
  toStruct_PositionOfOccupants(in.position_of_occupants, out.positionOfOccupants);
  toStruct_VehicleMass(in.vehicle_mass, out.vehicleMass);
  toStruct_RequestResponseIndication(in.request_response_indication, out.requestResponseIndication);
}

}
