// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/denm_en302637_3/DENM-PDU-Descriptions.asn \
  asn1/raw/denm_en302637_3/cdd/ITS-Container.asn \
  -t \
  denm \
  -o \
  etsi_its_conversion/etsi_its_denm_conversion/include/etsi_its_denm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
LightBarSirenInUse ::= BIT STRING {
    lightBarActivated (0),
    sirenActivated (1)
} (SIZE(2))
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_denm_coding/denm_LightBarSirenInUse.h>
#include <etsi_its_denm_coding/BIT_STRING.h>
#include <etsi_its_primitives_conversion/convertBIT_STRING.h>
#include <etsi_its_denm_msgs/msg/light_bar_siren_in_use.hpp>
namespace denm_msgs = etsi_its_denm_msgs::msg;


namespace etsi_its_denm_conversion {

void toRos_LightBarSirenInUse(const denm_LightBarSirenInUse_t& in, denm_msgs::LightBarSirenInUse& out) {
  etsi_its_primitives_conversion::toRos_BIT_STRING(in, out.value);
  out.bits_unused = in.bits_unused;
}

void toStruct_LightBarSirenInUse(const denm_msgs::LightBarSirenInUse& in, denm_LightBarSirenInUse_t& out) {
  memset(&out, 0, sizeof(denm_LightBarSirenInUse_t));
  etsi_its_primitives_conversion::toStruct_BIT_STRING(in.value, out);
  out.bits_unused = in.bits_unused;
}

}
