/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_uulm_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_H_
#define	_mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_H_


#include <etsi_its_mcm_uulm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_uulm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode {
	mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_unavailable	= 0,
	mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_wildAnimals	= 1,
	mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_herdOfAnimals	= 2,
	mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_smallAnimals	= 3,
	mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_largeAnimals	= 4,
	mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_wildAnimalsSmall	= 5,
	mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_wildAnimalsLarge	= 6,
	mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_domesticAnimals	= 7,
	mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_domesticAnimalsSmall	= 8,
	mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_domesticAnimalsLarge	= 9
} e_mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode;

/* mcm_uulm_HazardousLocation-AnimalOnTheRoadSubCauseCode */
typedef long	 mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode;
asn_struct_free_f mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_free;
asn_struct_print_f mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_print;
asn_constr_check_f mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_constraint;
per_type_decoder_f mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_decode_uper;
per_type_encoder_f mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_encode_uper;
per_type_decoder_f mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_decode_aper;
per_type_encoder_f mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_uulm_HazardousLocation_AnimalOnTheRoadSubCauseCode_H_ */
#include <etsi_its_mcm_uulm_coding/asn_internal.h>
