/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN1C-UsefulInformationObjectClasses"
 * 	found in "/usr/local/share/asn1c/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1"
 * 	`asn1c -fcompound-names -fprefix=mcm_uulm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_uulm_EXTERNAL_H_
#define	_mcm_uulm_EXTERNAL_H_


#include <etsi_its_mcm_uulm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_uulm_coding/OBJECT_IDENTIFIER.h>
#include <etsi_its_mcm_uulm_coding/NativeInteger.h>
#include <etsi_its_mcm_uulm_coding/ObjectDescriptor.h>
#include <etsi_its_mcm_uulm_coding/ANY.h>
#include <etsi_its_mcm_uulm_coding/OCTET_STRING.h>
#include <etsi_its_mcm_uulm_coding/BIT_STRING.h>
#include <etsi_its_mcm_uulm_coding/constr_CHOICE.h>
#include <etsi_its_mcm_uulm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_uulm_EXTERNAL__encoding_PR {
	mcm_uulm_EXTERNAL__encoding_PR_NOTHING,	/* No components present */
	mcm_uulm_EXTERNAL__encoding_PR_single_ASN1_type,
	mcm_uulm_EXTERNAL__encoding_PR_octet_aligned,
	mcm_uulm_EXTERNAL__encoding_PR_arbitrary
} mcm_uulm_EXTERNAL__encoding_PR;

/* mcm_uulm_EXTERNAL */
typedef struct mcm_uulm_EXTERNAL {
	OBJECT_IDENTIFIER_t	*direct_reference;	/* OPTIONAL */
	long	*indirect_reference;	/* OPTIONAL */
	ObjectDescriptor_t	*data_value_descriptor;	/* OPTIONAL */
	struct mcm_uulm_EXTERNAL__encoding {
		mcm_uulm_EXTERNAL__encoding_PR present;
		union mcm_uulm_EXTERNAL__mcm_uulm_encoding_u {
			ANY_t	 single_ASN1_type;
			OCTET_STRING_t	 octet_aligned;
			BIT_STRING_t	 arbitrary;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} encoding;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} mcm_uulm_EXTERNAL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_mcm_uulm_EXTERNAL;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_uulm_EXTERNAL_H_ */
#include <etsi_its_mcm_uulm_coding/asn_internal.h>
