/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=mcm_uulm_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_mcm_uulm_PathId_H_
#define	_mcm_uulm_PathId_H_


#include <etsi_its_mcm_uulm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_uulm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum mcm_uulm_PathId {
	mcm_uulm_PathId_noPath	= 0,
	mcm_uulm_PathId_path1	= 1,
	mcm_uulm_PathId_path2	= 2,
	mcm_uulm_PathId_path3	= 3,
	mcm_uulm_PathId_path4	= 4,
	mcm_uulm_PathId_path5	= 5,
	mcm_uulm_PathId_path6	= 6,
	mcm_uulm_PathId_path7	= 7,
	mcm_uulm_PathId_pathExtended1	= 8,
	mcm_uulm_PathId_pathExtended2	= 9,
	mcm_uulm_PathId_pathExtended3	= 10,
	mcm_uulm_PathId_pathExtended4	= 11,
	mcm_uulm_PathId_pathExtended5	= 12,
	mcm_uulm_PathId_pathExtended6	= 13,
	mcm_uulm_PathId_pathExtended7	= 14
} e_mcm_uulm_PathId;

/* mcm_uulm_PathId */
typedef long	 mcm_uulm_PathId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_mcm_uulm_PathId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_mcm_uulm_PathId;
asn_struct_free_f mcm_uulm_PathId_free;
asn_struct_print_f mcm_uulm_PathId_print;
asn_constr_check_f mcm_uulm_PathId_constraint;
jer_type_encoder_f mcm_uulm_PathId_encode_jer;
per_type_decoder_f mcm_uulm_PathId_decode_uper;
per_type_encoder_f mcm_uulm_PathId_encode_uper;
per_type_decoder_f mcm_uulm_PathId_decode_aper;
per_type_encoder_f mcm_uulm_PathId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _mcm_uulm_PathId_H_ */
#include <etsi_its_mcm_uulm_coding/asn_internal.h>
