# ------------------------------------------------------------------------------
# ImpactReductionContainer ::= SEQUENCE {
# 	heightLonCarrLeft HeightLonCarr,
# 	heightLonCarrRight HeightLonCarr,
# 	posLonCarrLeft PosLonCarr,
# 	posLonCarrRight PosLonCarr,
# 	positionOfPillars PositionOfPillars,
# 	posCentMass PosCentMass,
# 	wheelBaseVehicle WheelBaseVehicle,
# 	turningRadius TurningRadius,
# 	posFrontAx PosFrontAx,
# 	positionOfOccupants PositionOfOccupants,
# 	vehicleMass VehicleMass,
# 	requestResponseIndication RequestResponseIndication
# }
# ------------------------------------------------------------------------------

HeightLonCarr heightLonCarrLeft

HeightLonCarr heightLonCarrRight

PosLonCarr posLonCarrLeft

PosLonCarr posLonCarrRight

PositionOfPillars positionOfPillars

PosCentMass posCentMass

WheelBaseVehicle wheelBaseVehicle

TurningRadius turningRadius

PosFrontAx posFrontAx

PositionOfOccupants positionOfOccupants

VehicleMass vehicleMass

RequestResponseIndication requestResponseIndication
