/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=cpm_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_cpm_DeltaAltitude_H_
#define	_cpm_DeltaAltitude_H_


#include <etsi_its_cpm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_cpm_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum cpm_DeltaAltitude {
	cpm_DeltaAltitude_negativeOutOfRange	= -12700,
	cpm_DeltaAltitude_positiveOutOfRange	= 12799,
	cpm_DeltaAltitude_unavailable	= 12800
} e_cpm_DeltaAltitude;

/* cpm_DeltaAltitude */
typedef long	 cpm_DeltaAltitude_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_cpm_DeltaAltitude_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_cpm_DeltaAltitude;
asn_struct_free_f cpm_DeltaAltitude_free;
asn_struct_print_f cpm_DeltaAltitude_print;
asn_constr_check_f cpm_DeltaAltitude_constraint;
per_type_decoder_f cpm_DeltaAltitude_decode_uper;
per_type_encoder_f cpm_DeltaAltitude_encode_uper;
per_type_decoder_f cpm_DeltaAltitude_decode_aper;
per_type_encoder_f cpm_DeltaAltitude_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _cpm_DeltaAltitude_H_ */
#include <etsi_its_cpm_coding/asn_internal.h>
