/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=cpm_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_cpm_InterferenceManagementZoneType_H_
#define	_cpm_InterferenceManagementZoneType_H_


#include <etsi_its_cpm_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_cpm_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum cpm_InterferenceManagementZoneType {
	cpm_InterferenceManagementZoneType_permanentCenDsrcTolling	= 0,
	cpm_InterferenceManagementZoneType_temporaryCenDsrcTolling	= 1,
	cpm_InterferenceManagementZoneType_unavailable	= 2,
	cpm_InterferenceManagementZoneType_urbanRail	= 3,
	cpm_InterferenceManagementZoneType_satelliteStation	= 4,
	cpm_InterferenceManagementZoneType_fixedLinks	= 5
	/*
	 * Enumeration is extensible
	 */
} e_cpm_InterferenceManagementZoneType;

/* cpm_InterferenceManagementZoneType */
typedef long	 cpm_InterferenceManagementZoneType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_cpm_InterferenceManagementZoneType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_cpm_InterferenceManagementZoneType;
extern const asn_INTEGER_specifics_t asn_SPC_cpm_InterferenceManagementZoneType_specs_1;
asn_struct_free_f cpm_InterferenceManagementZoneType_free;
asn_struct_print_f cpm_InterferenceManagementZoneType_print;
asn_constr_check_f cpm_InterferenceManagementZoneType_constraint;
per_type_decoder_f cpm_InterferenceManagementZoneType_decode_uper;
per_type_encoder_f cpm_InterferenceManagementZoneType_encode_uper;
per_type_decoder_f cpm_InterferenceManagementZoneType_decode_aper;
per_type_encoder_f cpm_InterferenceManagementZoneType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _cpm_InterferenceManagementZoneType_H_ */
#include <etsi_its_cpm_coding/asn_internal.h>
