/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=cpm_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_cpm_LongitudinalLanePosition_H_
#define	_cpm_LongitudinalLanePosition_H_


#include <etsi_its_cpm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_cpm_coding/cpm_LongitudinalLanePositionValue.h"
#include "etsi_its_cpm_coding/cpm_LongitudinalLanePositionConfidence.h"
#include <etsi_its_cpm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* cpm_LongitudinalLanePosition */
typedef struct cpm_LongitudinalLanePosition {
	cpm_LongitudinalLanePositionValue_t	 longitudinalLanePositionValue;
	cpm_LongitudinalLanePositionConfidence_t	 longitudinalLanePositionConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} cpm_LongitudinalLanePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_cpm_LongitudinalLanePosition;
extern asn_SEQUENCE_specifics_t asn_SPC_cpm_LongitudinalLanePosition_specs_1;
extern asn_TYPE_member_t asn_MBR_cpm_LongitudinalLanePosition_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _cpm_LongitudinalLanePosition_H_ */
#include <etsi_its_cpm_coding/asn_internal.h>
