/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PerceptionRegionContainer"
 * 	found in "/input/CPM-PerceptionRegionContainer.asn"
 * 	`asn1c -fcompound-names -no-gen-example -gen-UPER`
 */


/* Including external dependencies */
#include "etsi_its_cpm_coding/Identifier2B.h"
#include <etsi_its_cpm_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_cpm_coding/constr_SEQUENCE_OF.h>
#ifndef	_PerceivedObjectIds_H_
#define	_PerceivedObjectIds_H_


#include <etsi_its_cpm_coding/asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PerceivedObjectIds */
typedef struct PerceivedObjectIds {
	A_SEQUENCE_OF(Identifier2B_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PerceivedObjectIds_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PerceivedObjectIds;
extern asn_SET_OF_specifics_t asn_SPC_PerceivedObjectIds_specs_1;
extern asn_TYPE_member_t asn_MBR_PerceivedObjectIds_1[1];
extern asn_per_constraints_t asn_PER_type_PerceivedObjectIds_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PerceivedObjectIds_H_ */
#include <etsi_its_cpm_coding/asn_internal.h>
