/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -no-gen-example -gen-UPER`
 */


/* Including external dependencies */
#include <etsi_its_cpm_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_cpm_coding/constr_SEQUENCE_OF.h>
#ifndef	_SequenceOfTrajectoryInterceptionIndication_H_
#define	_SequenceOfTrajectoryInterceptionIndication_H_


#include <etsi_its_cpm_coding/asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TrajectoryInterceptionIndication;

/* SequenceOfTrajectoryInterceptionIndication */
typedef struct SequenceOfTrajectoryInterceptionIndication {
	A_SEQUENCE_OF(struct TrajectoryInterceptionIndication) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfTrajectoryInterceptionIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfTrajectoryInterceptionIndication;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_cpm_coding/TrajectoryInterceptionIndication.h"

#endif	/* _SequenceOfTrajectoryInterceptionIndication_H_ */
#include <etsi_its_cpm_coding/asn_internal.h>
