/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -no-gen-example -gen-UPER`
 */


/* Including external dependencies */
#include "etsi_its_cpm_coding/Wgs84AngleValue.h"
#include "etsi_its_cpm_coding/Wgs84AngleConfidence.h"
#include <etsi_its_cpm_coding/constr_SEQUENCE.h>
#ifndef	_Wgs84Angle_H_
#define	_Wgs84Angle_H_


#include <etsi_its_cpm_coding/asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Wgs84Angle */
typedef struct Wgs84Angle {
	Wgs84AngleValue_t	 value;
	Wgs84AngleConfidence_t	 confidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Wgs84Angle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Wgs84Angle;
extern asn_SEQUENCE_specifics_t asn_SPC_Wgs84Angle_specs_1;
extern asn_TYPE_member_t asn_MBR_Wgs84Angle_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Wgs84Angle_H_ */
#include <etsi_its_cpm_coding/asn_internal.h>
