# ------------------------------------------------------------------------------
# BasicVehicleRole ::= ENUMERATED {
#   basicVehicle     (0),
#   publicTransport  (1),
#   specialTransport (2),
#   dangerousGoods   (3),
#   roadWork         (4),
#   roadRescue       (5),
#   emergency        (6),
#   safetyCar        (7),
#   none-unknown     (8),
#   truck            (9),
#   motorcycle      (10),
#   roadSideSource  (11),
#   police          (12),
#   fire            (13),
#   ambulance       (14),
#   dot             (15),
#   transit         (16),
#   slowMoving      (17),
#   stopNgo         (18),
#   cyclist         (19),
#   pedestrian      (20),
#   nonMotorized    (21),
#   military        (22),
#   ...   
# }  
# ------------------------------------------------------------------------------

uint8 BASIC_VEHICLE = 0
uint8 PUBLIC_TRANSPORT = 1
uint8 SPECIAL_TRANSPORT = 2
uint8 DANGEROUS_GOODS = 3
uint8 ROAD_WORK = 4
uint8 ROAD_RESCUE = 5
uint8 EMERGENCY = 6
uint8 SAFETY_CAR = 7
uint8 NONEUNKNOWN = 8
uint8 TRUCK = 9
uint8 MOTORCYCLE = 10
uint8 ROAD_SIDE_SOURCE = 11
uint8 POLICE = 12
uint8 FIRE = 13
uint8 AMBULANCE = 14
uint8 DOT = 15
uint8 TRANSIT = 16
uint8 SLOW_MOVING = 17
uint8 STOP_NGO = 18
uint8 CYCLIST = 19
uint8 PEDESTRIAN = 20
uint8 NON_MOTORIZED = 21
uint8 MILITARY = 22
uint8 value
