# ------------------------------------------------------------------------------
# DDateTime ::= SEQUENCE {
#    year    DYear    OPTIONAL,    
#    month   DMonth   OPTIONAL,   
#    day     DDay     OPTIONAL,  
#    hour    DHour    OPTIONAL,   
#    minute  DMinute  OPTIONAL,  
#    second  DSecond  OPTIONAL,  
#    offset  DOffset  OPTIONAL
#    }
# ------------------------------------------------------------------------------

# optional: True
DYear year

# optional: True
DMonth month

# optional: True
DDay day

# optional: True
DHour hour

# optional: True
DMinute minute

# optional: True
DSecond second

# optional: True
DOffset offset
