# ------------------------------------------------------------------------------
# ElevationConfidence ::= ENUMERATED {
#    unavailable (0),
#    elev-500-00 (1),
#    elev-200-00 (2),
#    elev-100-00 (3),
#    elev-050-00 (4),
#    elev-020-00 (5),
#    elev-010-00 (6),
#    elev-005-00 (7),
#    elev-002-00 (8),
#    elev-001-00 (9),
#    elev-000-50 (10),
#    elev-000-20 (11),
#    elev-000-10 (12),
#    elev-000-05 (13),
#    elev-000-02 (14),
#    elev-000-01 (15)
#    }
# ------------------------------------------------------------------------------

uint8 UNAVAILABLE = 0
uint8 ELEV_5_0_0_0_0 = 1
uint8 ELEV_2_0_0_0_0 = 2
uint8 ELEV_1_0_0_0_0 = 3
uint8 ELEV_0_5_0_0_0 = 4
uint8 ELEV_0_2_0_0_0 = 5
uint8 ELEV_0_1_0_0_0 = 6
uint8 ELEV_0_0_5_0_0 = 7
uint8 ELEV_0_0_2_0_0 = 8
uint8 ELEV_0_0_1_0_0 = 9
uint8 ELEV_0_0_0_5_0 = 10
uint8 ELEV_0_0_0_2_0 = 11
uint8 ELEV_0_0_0_1_0 = 12
uint8 ELEV_0_0_0_0_5 = 13
uint8 ELEV_0_0_0_0_2 = 14
uint8 ELEV_0_0_0_0_1 = 15
uint8 value
