# ------------------------------------------------------------------------------
# LaneAttributes-Striping ::= BIT STRING { 
#   stripeToConnectingLanesRevocableLane      (0),
#   stripeDrawOnLeft                          (1),
#   stripeDrawOnRight                         (2),
#   stripeToConnectingLanesLeft               (3),
#   stripeToConnectingLanesRight              (4),
#   stripeToConnectingLanesAhead              (5)
# } (SIZE (16))
# ------------------------------------------------------------------------------

# named-bits: [('stripeToConnectingLanesRevocableLane', '0'), ('stripeDrawOnLeft', '1'), ('stripeDrawOnRight', '2'), ('stripeToConnectingLanesLeft', '3'), ('stripeToConnectingLanesRight', '4'), ('stripeToConnectingLanesAhead', '5')]
# size: [16]
string value
