# ------------------------------------------------------------------------------
# LaneAttributes-TrackedVehicle ::= BIT STRING { 
#   spec-RevocableLane         (0),
#   spec-commuterRailRoadTrack (1), 
#   spec-lightRailRoadTrack    (2),
#   spec-heavyRailRoadTrack    (3),
#   spec-otherRailType         (4)
# } (SIZE (16))
# ------------------------------------------------------------------------------

# named-bits: [('spec-RevocableLane', '0'), ('spec-commuterRailRoadTrack', '1'), ('spec-lightRailRoadTrack', '2'), ('spec-heavyRailRoadTrack', '3'), ('spec-otherRailType', '4')]
# size: [16]
string value
