# ------------------------------------------------------------------------------
# RequestSubRole ::= ENUMERATED {
#   requestSubRoleUnKnown    (0),
#   requestSubRole1          (1),
#   requestSubRole2          (2),
#   requestSubRole3          (3),
#   requestSubRole4          (4),
#   requestSubRole5          (5),
#   requestSubRole6          (6),
#   requestSubRole7          (7),
#   requestSubRole8          (8),
#   requestSubRole9          (9),
#   requestSubRole10        (10),
#   requestSubRole11        (11),
#   requestSubRole12        (12),
#   requestSubRole13        (13),
#   requestSubRole14        (14),
#   requestSubRoleReserved  (15)
# }
# ------------------------------------------------------------------------------

uint8 REQUEST_SUB_ROLE_UN_KNOWN = 0
uint8 REQUEST_SUB_ROLE_1 = 1
uint8 REQUEST_SUB_ROLE_2 = 2
uint8 REQUEST_SUB_ROLE_3 = 3
uint8 REQUEST_SUB_ROLE_4 = 4
uint8 REQUEST_SUB_ROLE_5 = 5
uint8 REQUEST_SUB_ROLE_6 = 6
uint8 REQUEST_SUB_ROLE_7 = 7
uint8 REQUEST_SUB_ROLE_8 = 8
uint8 REQUEST_SUB_ROLE_9 = 9
uint8 REQUEST_SUB_ROLE_1_0 = 10
uint8 REQUEST_SUB_ROLE_1_1 = 11
uint8 REQUEST_SUB_ROLE_1_2 = 12
uint8 REQUEST_SUB_ROLE_1_3 = 13
uint8 REQUEST_SUB_ROLE_1_4 = 14
uint8 REQUEST_SUB_ROLE_RESERVED = 15
uint8 value
