# ------------------------------------------------------------------------------
# VehicleType ::= ENUMERATED {
#   none                 (0),
#   unknown              (1),
#   special              (2),
#   moto                 (3),
#   car                  (4),
#   carOther             (5),
#   bus                  (6),
#   axleCnt2             (7),
#   axleCnt3             (8),
#   axleCnt4             (9),
#   axleCnt4Trailer      (10),
#   axleCnt5Trailer      (11),
#   axleCnt6Trailer      (12),
#   axleCnt5MultiTrailer (13),
#   axleCnt6MultiTrailer (14),
#   axleCnt7MultiTrailer (15),
#   ...  
# } 
# ------------------------------------------------------------------------------

uint8 NONE = 0
uint8 UNKNOWN = 1
uint8 SPECIAL = 2
uint8 MOTO = 3
uint8 CAR = 4
uint8 CAR_OTHER = 5
uint8 BUS = 6
uint8 AXLE_CNT_2 = 7
uint8 AXLE_CNT_3 = 8
uint8 AXLE_CNT_4 = 9
uint8 AXLE_CNT_4_TRAILER = 10
uint8 AXLE_CNT_5_TRAILER = 11
uint8 AXLE_CNT_6_TRAILER = 12
uint8 AXLE_CNT_5_MULTI_TRAILER = 13
uint8 AXLE_CNT_6_MULTI_TRAILER = 14
uint8 AXLE_CNT_7_MULTI_TRAILER = 15
uint8 value
