/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=cpm_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_cpm_ts_VruSubProfileBicyclist_H_
#define	_cpm_ts_VruSubProfileBicyclist_H_


#include <etsi_its_cpm_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_cpm_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum cpm_ts_VruSubProfileBicyclist {
	cpm_ts_VruSubProfileBicyclist_unavailable	= 0,
	cpm_ts_VruSubProfileBicyclist_bicyclist	= 1,
	cpm_ts_VruSubProfileBicyclist_wheelchair_user	= 2,
	cpm_ts_VruSubProfileBicyclist_horse_and_rider	= 3,
	cpm_ts_VruSubProfileBicyclist_rollerskater	= 4,
	cpm_ts_VruSubProfileBicyclist_e_scooter	= 5,
	cpm_ts_VruSubProfileBicyclist_personal_transporter	= 6,
	cpm_ts_VruSubProfileBicyclist_pedelec	= 7,
	cpm_ts_VruSubProfileBicyclist_speed_pedelec	= 8,
	cpm_ts_VruSubProfileBicyclist_max	= 15
} e_cpm_ts_VruSubProfileBicyclist;

/* cpm_ts_VruSubProfileBicyclist */
typedef long	 cpm_ts_VruSubProfileBicyclist_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_cpm_ts_VruSubProfileBicyclist_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_cpm_ts_VruSubProfileBicyclist;
extern const asn_INTEGER_specifics_t asn_SPC_cpm_ts_VruSubProfileBicyclist_specs_1;
asn_struct_free_f cpm_ts_VruSubProfileBicyclist_free;
asn_struct_print_f cpm_ts_VruSubProfileBicyclist_print;
asn_constr_check_f cpm_ts_VruSubProfileBicyclist_constraint;
per_type_decoder_f cpm_ts_VruSubProfileBicyclist_decode_uper;
per_type_encoder_f cpm_ts_VruSubProfileBicyclist_encode_uper;
per_type_decoder_f cpm_ts_VruSubProfileBicyclist_decode_aper;
per_type_encoder_f cpm_ts_VruSubProfileBicyclist_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _cpm_ts_VruSubProfileBicyclist_H_ */
#include <etsi_its_cpm_ts_coding/asn_internal.h>
