/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=cpm_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_cpm_ts_LaneType_H_
#define	_cpm_ts_LaneType_H_


#include <etsi_its_cpm_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_cpm_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum cpm_ts_LaneType {
	cpm_ts_LaneType_traffic	= 0,
	cpm_ts_LaneType_through	= 1,
	cpm_ts_LaneType_reversible	= 2,
	cpm_ts_LaneType_acceleration	= 3,
	cpm_ts_LaneType_deceleration	= 4,
	cpm_ts_LaneType_leftHandTurning	= 5,
	cpm_ts_LaneType_rightHandTurning	= 6,
	cpm_ts_LaneType_dedicatedVehicle	= 7,
	cpm_ts_LaneType_bus	= 8,
	cpm_ts_LaneType_taxi	= 9,
	cpm_ts_LaneType_hov	= 10,
	cpm_ts_LaneType_hot	= 11,
	cpm_ts_LaneType_pedestrian	= 12,
	cpm_ts_LaneType_cycleLane	= 13,
	cpm_ts_LaneType_median	= 14,
	cpm_ts_LaneType_striping	= 15,
	cpm_ts_LaneType_trackedVehicle	= 16,
	cpm_ts_LaneType_parking	= 17,
	cpm_ts_LaneType_emergency	= 18,
	cpm_ts_LaneType_verge	= 19,
	cpm_ts_LaneType_minimumRiskManoeuvre	= 20,
	cpm_ts_LaneType_unknown	= 31
} e_cpm_ts_LaneType;

/* cpm_ts_LaneType */
typedef long	 cpm_ts_LaneType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_cpm_ts_LaneType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_cpm_ts_LaneType;
asn_struct_free_f cpm_ts_LaneType_free;
asn_struct_print_f cpm_ts_LaneType_print;
asn_constr_check_f cpm_ts_LaneType_constraint;
jer_type_encoder_f cpm_ts_LaneType_encode_jer;
per_type_decoder_f cpm_ts_LaneType_decode_uper;
per_type_encoder_f cpm_ts_LaneType_encode_uper;
per_type_decoder_f cpm_ts_LaneType_decode_aper;
per_type_encoder_f cpm_ts_LaneType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _cpm_ts_LaneType_H_ */
#include <etsi_its_cpm_ts_coding/asn_internal.h>
