/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=cpm_ts_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_cpm_ts_VruMovementControl_H_
#define	_cpm_ts_VruMovementControl_H_


#include <etsi_its_cpm_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_cpm_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum cpm_ts_VruMovementControl {
	cpm_ts_VruMovementControl_unavailable	= 0,
	cpm_ts_VruMovementControl_braking	= 1,
	cpm_ts_VruMovementControl_hardBraking	= 2,
	cpm_ts_VruMovementControl_stopPedaling	= 3,
	cpm_ts_VruMovementControl_brakingAndStopPedaling	= 4,
	cpm_ts_VruMovementControl_hardBrakingAndStopPedaling	= 5,
	cpm_ts_VruMovementControl_noReaction	= 6,
	cpm_ts_VruMovementControl_max	= 255
} e_cpm_ts_VruMovementControl;

/* cpm_ts_VruMovementControl */
typedef long	 cpm_ts_VruMovementControl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_cpm_ts_VruMovementControl;
asn_struct_free_f cpm_ts_VruMovementControl_free;
asn_struct_print_f cpm_ts_VruMovementControl_print;
asn_constr_check_f cpm_ts_VruMovementControl_constraint;
per_type_decoder_f cpm_ts_VruMovementControl_decode_uper;
per_type_encoder_f cpm_ts_VruMovementControl_encode_uper;
per_type_decoder_f cpm_ts_VruMovementControl_decode_aper;
per_type_encoder_f cpm_ts_VruMovementControl_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _cpm_ts_VruMovementControl_H_ */
#include <etsi_its_cpm_ts_coding/asn_internal.h>
