/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=cpm_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_cpm_ts_ExteriorLights_H_
#define	_cpm_ts_ExteriorLights_H_


#include <etsi_its_cpm_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_cpm_ts_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum cpm_ts_ExteriorLights {
	cpm_ts_ExteriorLights_lowBeamHeadlightsOn	= 0,
	cpm_ts_ExteriorLights_highBeamHeadlightsOn	= 1,
	cpm_ts_ExteriorLights_leftTurnSignalOn	= 2,
	cpm_ts_ExteriorLights_rightTurnSignalOn	= 3,
	cpm_ts_ExteriorLights_daytimeRunningLightsOn	= 4,
	cpm_ts_ExteriorLights_reverseLightOn	= 5,
	cpm_ts_ExteriorLights_fogLightOn	= 6,
	cpm_ts_ExteriorLights_parkingLightsOn	= 7
} e_cpm_ts_ExteriorLights;

/* cpm_ts_ExteriorLights */
typedef BIT_STRING_t	 cpm_ts_ExteriorLights_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_cpm_ts_ExteriorLights_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_cpm_ts_ExteriorLights;
asn_struct_free_f cpm_ts_ExteriorLights_free;
asn_struct_print_f cpm_ts_ExteriorLights_print;
asn_constr_check_f cpm_ts_ExteriorLights_constraint;
jer_type_encoder_f cpm_ts_ExteriorLights_encode_jer;
per_type_decoder_f cpm_ts_ExteriorLights_decode_uper;
per_type_encoder_f cpm_ts_ExteriorLights_encode_uper;
per_type_decoder_f cpm_ts_ExteriorLights_decode_aper;
per_type_encoder_f cpm_ts_ExteriorLights_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _cpm_ts_ExteriorLights_H_ */
#include <etsi_its_cpm_ts_coding/asn_internal.h>
