/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=cpm_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_cpm_ts_HeadingValue_H_
#define	_cpm_ts_HeadingValue_H_


#include <etsi_its_cpm_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_cpm_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum cpm_ts_HeadingValue {
	cpm_ts_HeadingValue_wgs84North	= 0,
	cpm_ts_HeadingValue_wgs84East	= 900,
	cpm_ts_HeadingValue_wgs84South	= 1800,
	cpm_ts_HeadingValue_wgs84West	= 2700,
	cpm_ts_HeadingValue_doNotUse	= 3600,
	cpm_ts_HeadingValue_unavailable	= 3601
} e_cpm_ts_HeadingValue;

/* cpm_ts_HeadingValue */
typedef long	 cpm_ts_HeadingValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_cpm_ts_HeadingValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_cpm_ts_HeadingValue;
asn_struct_free_f cpm_ts_HeadingValue_free;
asn_struct_print_f cpm_ts_HeadingValue_print;
asn_constr_check_f cpm_ts_HeadingValue_constraint;
jer_type_encoder_f cpm_ts_HeadingValue_encode_jer;
per_type_decoder_f cpm_ts_HeadingValue_decode_uper;
per_type_encoder_f cpm_ts_HeadingValue_encode_uper;
per_type_decoder_f cpm_ts_HeadingValue_decode_aper;
per_type_encoder_f cpm_ts_HeadingValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _cpm_ts_HeadingValue_H_ */
#include <etsi_its_cpm_ts_coding/asn_internal.h>
