services:

  zenoh-router:
    image: ghcr.io/ika-rwth-aachen/etsi_its_messages:latest
    extends:
      file: ./compose-essentials.template.yml
      service: zenoh-router

  etsi_its_conversion:
    image: ghcr.io/ika-rwth-aachen/etsi_its_messages:latest
    extends:
      file: ./compose-essentials.template.yml
      service: ros2-zenoh-service
    command: ros2 launch etsi_its_conversion converter.launch.py use_sim_time:=true input_topic_udp:=/v2x/raw
    volumes:
      - ./config/etsi_its_conversion/params.yml:/docker-ros/ws/install/etsi_its_conversion/share/etsi_its_conversion/config/params.yml:ro

  etsi_its_rviz:
    image: ghcr.io/ika-rwth-aachen/etsi_its_messages:latest
    extends:
      file: ./compose-essentials.template.yml
      service: ros2-zenoh-gpu-x11-service
    command: ros2 launch etsi_its_rviz_plugins demo.launch.py use_sim_time:=true lat:=${RVIZ_LAT} lon:=${RVIZ_LON}
    volumes:
      - ./v2aix.rviz:/docker-ros/ws/install/etsi_its_rviz_plugins/share/etsi_its_rviz_plugins/config/demo.rviz:ro

  v2aix_bag_player:
    image: ghcr.io/ika-rwth-aachen/etsi_its_messages:latest
    extends:
      file: ./compose-essentials.template.yml
      service: ros2-zenoh-service
    command: ros2 bag play /bags/${BAG_PATH} --clock -l
    environment:
      - BAG_PATH
    volumes:
      - ${BAG_DIR}:/bags:ro
