/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=denm_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_denm_ProtectedCommunicationZone_H_
#define	_denm_ProtectedCommunicationZone_H_


#include <etsi_its_denm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_denm_coding/denm_ProtectedZoneType.h"
#include "etsi_its_denm_coding/denm_TimestampIts.h"
#include "etsi_its_denm_coding/denm_Latitude.h"
#include "etsi_its_denm_coding/denm_Longitude.h"
#include "etsi_its_denm_coding/denm_ProtectedZoneRadius.h"
#include "etsi_its_denm_coding/denm_ProtectedZoneID.h"
#include <etsi_its_denm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* denm_ProtectedCommunicationZone */
typedef struct denm_ProtectedCommunicationZone {
	denm_ProtectedZoneType_t	 protectedZoneType;
	denm_TimestampIts_t	*expiryTime;	/* OPTIONAL */
	denm_Latitude_t	 protectedZoneLatitude;
	denm_Longitude_t	 protectedZoneLongitude;
	denm_ProtectedZoneRadius_t	*protectedZoneRadius;	/* OPTIONAL */
	denm_ProtectedZoneID_t	*protectedZoneID;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} denm_ProtectedCommunicationZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_denm_ProtectedCommunicationZone;
extern asn_SEQUENCE_specifics_t asn_SPC_denm_ProtectedCommunicationZone_specs_1;
extern asn_TYPE_member_t asn_MBR_denm_ProtectedCommunicationZone_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _denm_ProtectedCommunicationZone_H_ */
#include <etsi_its_denm_coding/asn_internal.h>
