/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=denm_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_denm_DeltaReferencePosition_H_
#define	_denm_DeltaReferencePosition_H_


#include <etsi_its_denm_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_denm_coding/denm_DeltaLatitude.h"
#include "etsi_its_denm_coding/denm_DeltaLongitude.h"
#include "etsi_its_denm_coding/denm_DeltaAltitude.h"
#include <etsi_its_denm_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* denm_DeltaReferencePosition */
typedef struct denm_DeltaReferencePosition {
	denm_DeltaLatitude_t	 deltaLatitude;
	denm_DeltaLongitude_t	 deltaLongitude;
	denm_DeltaAltitude_t	 deltaAltitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} denm_DeltaReferencePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_denm_DeltaReferencePosition;
extern asn_SEQUENCE_specifics_t asn_SPC_denm_DeltaReferencePosition_specs_1;
extern asn_TYPE_member_t asn_MBR_denm_DeltaReferencePosition_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _denm_DeltaReferencePosition_H_ */
#include <etsi_its_denm_coding/asn_internal.h>
