# ------------------------------------------------------------------------------
# CenDsrcTollingZone ::= SEQUENCE {
#     protectedZoneLatitude Latitude,
#     protectedZoneLongitude Longitude,
#     cenDsrcTollingZoneID CenDsrcTollingZoneID OPTIONAL,
#         ...
# }
# ------------------------------------------------------------------------------

Latitude protectedZoneLatitude

Longitude protectedZoneLongitude

# optional: True
CenDsrcTollingZoneID cenDsrcTollingZoneID
