# ------------------------------------------------------------------------------
# DeltaAltitude ::= INTEGER {oneCentimeterUp (1), oneCentimeterDown (-1), unavailable(12800)} (-12700..12800)
# ------------------------------------------------------------------------------

# restricted-to: [(-12700, 12800)]
int64 ONE_CENTIMETER_UP = 1
int64 ONE_CENTIMETER_DOWN = -1
int64 UNAVAILABLE = 12800
int64 value
