# ------------------------------------------------------------------------------
# DeltaLongitude ::= INTEGER {oneMicrodegreeEast (10), oneMicrodegreeWest (-10), unavailable(131072)} (-131071..131072)
# ------------------------------------------------------------------------------

# restricted-to: [(-131071, 131072)]
int64 ONE_MICRODEGREE_EAST = 10
int64 ONE_MICRODEGREE_WEST = -10
int64 UNAVAILABLE = 131072
int64 value
