# ------------------------------------------------------------------------------
# LongitudinalAccelerationValue ::= INTEGER {pointOneMeterPerSecSquaredForward(1), pointOneMeterPerSecSquaredBackward(-1), unavailable(161)} (-160 .. 161)
# ------------------------------------------------------------------------------

# restricted-to: [(-160, 161)]
int16 POINT_ONE_METER_PER_SEC_SQUARED_FORWARD = 1
int16 POINT_ONE_METER_PER_SEC_SQUARED_BACKWARD = -1
int16 UNAVAILABLE = 161
int16 value
