// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/cpm_ts103324/asn/CPM-PDU-Descriptions.asn \
  asn1/raw/cpm_ts103324/asn/CPM-OriginatingStationContainers.asn \
  asn1/raw/cpm_ts103324/asn/CPM-PerceivedObjectContainer.asn \
  asn1/raw/cpm_ts103324/asn/CPM-PerceptionRegionContainer.asn \
  asn1/raw/cpm_ts103324/asn/CPM-SensorInformationContainer.asn \
  asn1/patched/cpm_ts103324/asn/cdd/ETSI-ITS-CDD.asn \
  -t \
  cpm_ts \
  -o \
  etsi_its_conversion/etsi_its_cpm_ts_conversion/include/etsi_its_cpm_ts_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
*
 * This DF represents a acceleration vector in a cartesian coordinate system.
 
 * It shall include the following components: 
 * 
 * @field xAcceleration: the x component of the acceleration vector with the associated confidence value.
 * 
 * @field yAcceleration: the y component of the acceleration vector with the associated confidence value.
 *
 * @field zAcceleration: the optional z component of the acceleration vector with the associated confidence value.
 * 
 * @category: Kinematic information
 * @revision: Created in V2.1.1
 *
AccelerationCartesian::= SEQUENCE{
    xAcceleration      AccelerationComponent,
    yAcceleration      AccelerationComponent,
    zAcceleration      AccelerationComponent OPTIONAL
}            
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_cpm_ts_coding/cpm_ts_AccelerationCartesian.h>
#include <etsi_its_cpm_ts_conversion/convertAccelerationComponent.h>
#include <etsi_its_cpm_ts_msgs/msg/acceleration_cartesian.hpp>
namespace cpm_ts_msgs = etsi_its_cpm_ts_msgs::msg;


namespace etsi_its_cpm_ts_conversion {

void toRos_AccelerationCartesian(const cpm_ts_AccelerationCartesian_t& in, cpm_ts_msgs::AccelerationCartesian& out) {
  toRos_AccelerationComponent(in.xAcceleration, out.x_acceleration);
  toRos_AccelerationComponent(in.yAcceleration, out.y_acceleration);
  if (in.zAcceleration) {
    toRos_AccelerationComponent(*in.zAcceleration, out.z_acceleration);
    out.z_acceleration_is_present = true;
  }
}

void toStruct_AccelerationCartesian(const cpm_ts_msgs::AccelerationCartesian& in, cpm_ts_AccelerationCartesian_t& out) {
  memset(&out, 0, sizeof(cpm_ts_AccelerationCartesian_t));
  toStruct_AccelerationComponent(in.x_acceleration, out.xAcceleration);
  toStruct_AccelerationComponent(in.y_acceleration, out.yAcceleration);
  if (in.z_acceleration_is_present) {
    out.zAcceleration = (cpm_ts_AccelerationComponent_t*) calloc(1, sizeof(cpm_ts_AccelerationComponent_t));
    toStruct_AccelerationComponent(in.z_acceleration, *out.zAcceleration);
  }
}

}
