# ------------------------------------------------------------------------------
# RSUContainerHighFrequency ::= SEQUENCE {
# 	protectedCommunicationZonesRSU ProtectedCommunicationZonesRSU OPTIONAL,
# 	...
# }
# ------------------------------------------------------------------------------

# optional: True
ProtectedCommunicationZonesRSU protectedCommunicationZonesRSU
bool protectedCommunicationZonesRSU_isPresent
