# ------------------------------------------------------------------------------
# RSUContainerHighFrequency ::= SEQUENCE {
# 	protectedCommunicationZonesRSU ProtectedCommunicationZonesRSU OPTIONAL,
# 	...
# }
# ------------------------------------------------------------------------------

ProtectedCommunicationZonesRSU protectedCommunicationZonesRSU
bool protectedCommunicationZonesRSU_isPresent
