// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/patched/uulm_mcm_etsi/TS103561_LUKAS_MCM.asn \
  asn1/patched/uulm_mcm_etsi/ETSI-ITS-CDD.asn \
  -t \
  mcm_uulm \
  -o \
  etsi_its_conversion/etsi_its_mcm_uulm_conversion/include/etsi_its_mcm_uulm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
TerminationStatus ::= ENUMERATED {
	regularEnd                           (0),
	abortByReject                        (1),
	abortByTimeout                       (2),
	abortByConstraintViolation           (3),
	abortByEmergencyVehicleAppearance    (4),
	reasonUnknown                       (15)
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_mcm_uulm_coding/mcm_uulm_TerminationStatus.h>

#include <etsi_its_mcm_uulm_msgs/msg/termination_status.hpp>
namespace mcm_uulm_msgs = etsi_its_mcm_uulm_msgs::msg;


namespace etsi_its_mcm_uulm_conversion {

void toRos_TerminationStatus(const mcm_uulm_TerminationStatus_t& in, mcm_uulm_msgs::TerminationStatus& out) {
  out.value = in;
}

void toStruct_TerminationStatus(const mcm_uulm_msgs::TerminationStatus& in, mcm_uulm_TerminationStatus_t& out) {
  memset(&out, 0, sizeof(mcm_uulm_TerminationStatus_t));
  out = in.value;
}

}
