// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/patched/uulm_mcm_etsi/TS103561_LUKAS_MCM.asn \
  asn1/patched/uulm_mcm_etsi/ETSI-ITS-CDD.asn \
  -t \
  mcm_uulm \
  -o \
  etsi_its_conversion/etsi_its_mcm_uulm_conversion/include/etsi_its_mcm_uulm_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
McmParameters ::= SEQUENCE {
	basicContainer      BasicContainer,
	maneuverContainer   ManeuverContainer
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_mcm_uulm_coding/mcm_uulm_McmParameters.h>
#include <etsi_its_mcm_uulm_conversion/convertBasicContainer.h>
#include <etsi_its_mcm_uulm_conversion/convertManeuverContainer.h>
#include <etsi_its_mcm_uulm_msgs/msg/mcm_parameters.hpp>
namespace mcm_uulm_msgs = etsi_its_mcm_uulm_msgs::msg;


namespace etsi_its_mcm_uulm_conversion {

void toRos_McmParameters(const mcm_uulm_McmParameters_t& in, mcm_uulm_msgs::McmParameters& out) {
  toRos_BasicContainer(in.basicContainer, out.basic_container);
  toRos_ManeuverContainer(in.maneuverContainer, out.maneuver_container);
}

void toStruct_McmParameters(const mcm_uulm_msgs::McmParameters& in, mcm_uulm_McmParameters_t& out) {
  memset(&out, 0, sizeof(mcm_uulm_McmParameters_t));
  toStruct_BasicContainer(in.basic_container, out.basicContainer);
  toStruct_ManeuverContainer(in.maneuver_container, out.maneuverContainer);
}

}
