# ------------------------------------------------------------------------------
# AccelerationConfidence ::= INTEGER {pointOneMeterPerSecSquared(1), outOfRange(101), unavailable(102)} (0 .. 102)
# ------------------------------------------------------------------------------

# restricted-to: [(0, 102)]
int64 POINT_ONE_METER_PER_SEC_SQUARED = 1
int64 OUT_OF_RANGE = 101
int64 UNAVAILABLE = 102
int64 value
