# ------------------------------------------------------------------------------
# AltitudeValue ::= INTEGER {referenceEllipsoidSurface(0), oneCentimeter(1), unavailable(800001)} (-100000..800001)
# ------------------------------------------------------------------------------

int64 MIN = -100000
int64 MAX = 800001
int64 REFERENCE_ELLIPSOID_SURFACE = 0
int64 ONE_CENTIMETER = 1
int64 UNAVAILABLE = 800001
int64 value
