# ------------------------------------------------------------------------------
# CenDsrcTollingZone ::= SEQUENCE {
#     protectedZoneLatitude Latitude,
#     protectedZoneLongitude Longitude,
#     cenDsrcTollingZoneID CenDsrcTollingZoneID OPTIONAL,
#         ...
# }
# ------------------------------------------------------------------------------

Latitude protected_zone_latitude

Longitude protected_zone_longitude

CenDsrcTollingZoneID cen_dsrc_tolling_zone_i_d
bool cen_dsrc_tolling_zone_i_d_is_present

