# ------------------------------------------------------------------------------
# CurvatureConfidence ::= ENUMERATED {
#     onePerMeter-0-00002 (0),
#     onePerMeter-0-0001 (1),
#     onePerMeter-0-0005 (2),
#     onePerMeter-0-002 (3),
#     onePerMeter-0-01 (4),
#     onePerMeter-0-1 (5),
#     outOfRange (6),
#     unavailable (7)
# }
# ------------------------------------------------------------------------------

uint8 value
uint8 ONE_PER_METER_0_0_0_0_0_2 = 0
uint8 ONE_PER_METER_0_0_0_0_1 = 1
uint8 ONE_PER_METER_0_0_0_0_5 = 2
uint8 ONE_PER_METER_0_0_0_2 = 3
uint8 ONE_PER_METER_0_0_1 = 4
uint8 ONE_PER_METER_0_1 = 5
uint8 OUT_OF_RANGE = 6
uint8 UNAVAILABLE = 7

