# ------------------------------------------------------------------------------
# CurvatureConfidence ::= ENUMERATED {
#     onePerMeter-0-00002 (0),
#     onePerMeter-0-0001 (1),
#     onePerMeter-0-0005 (2),
#     onePerMeter-0-002 (3),
#     onePerMeter-0-01 (4),
#     onePerMeter-0-1 (5),
#     outOfRange (6),
#     unavailable (7)
# }
# ------------------------------------------------------------------------------

int64 ONE_PER_METER_0_0_0_0_0_2 = 0
int64 ONE_PER_METER_0_0_0_0_1 = 1
int64 ONE_PER_METER_0_0_0_0_5 = 2
int64 ONE_PER_METER_0_0_0_2 = 3
int64 ONE_PER_METER_0_0_1 = 4
int64 ONE_PER_METER_0_1 = 5
int64 OUT_OF_RANGE = 6
int64 UNAVAILABLE = 7
int64 value
