# ------------------------------------------------------------------------------
# DangerousGoodsBasic::= ENUMERATED {
#     explosives1(0),
#     explosives2(1),
#     explosives3(2),
#     explosives4(3),
#     explosives5(4),
#     explosives6(5),
#     flammableGases(6),
#     nonFlammableGases(7),
#     toxicGases(8),
#     flammableLiquids(9),
#     flammableSolids(10),
#     substancesLiableToSpontaneousCombustion(11),
#     substancesEmittingFlammableGasesUponContactWithWater(12),
#     oxidizingSubstances(13),
#     organicPeroxides(14),
#     toxicSubstances(15),
#     infectiousSubstances(16),
#     radioactiveMaterial(17),
#     corrosiveSubstances(18),
#     miscellaneousDangerousSubstances(19)
# }
# ------------------------------------------------------------------------------

uint8 value
uint8 EXPLOSIVES_1 = 0
uint8 EXPLOSIVES_2 = 1
uint8 EXPLOSIVES_3 = 2
uint8 EXPLOSIVES_4 = 3
uint8 EXPLOSIVES_5 = 4
uint8 EXPLOSIVES_6 = 5
uint8 FLAMMABLE_GASES = 6
uint8 NON_FLAMMABLE_GASES = 7
uint8 TOXIC_GASES = 8
uint8 FLAMMABLE_LIQUIDS = 9
uint8 FLAMMABLE_SOLIDS = 10
uint8 SUBSTANCES_LIABLE_TO_SPONTANEOUS_COMBUSTION = 11
uint8 SUBSTANCES_EMITTING_FLAMMABLE_GASES_UPON_CONTACT_WITH_WATER = 12
uint8 OXIDIZING_SUBSTANCES = 13
uint8 ORGANIC_PEROXIDES = 14
uint8 TOXIC_SUBSTANCES = 15
uint8 INFECTIOUS_SUBSTANCES = 16
uint8 RADIOACTIVE_MATERIAL = 17
uint8 CORROSIVE_SUBSTANCES = 18
uint8 MISCELLANEOUS_DANGEROUS_SUBSTANCES = 19

