# ------------------------------------------------------------------------------
# DangerousGoodsBasic::= ENUMERATED {
#     explosives1(0),
#     explosives2(1),
#     explosives3(2),
#     explosives4(3),
#     explosives5(4),
#     explosives6(5),
#     flammableGases(6),
#     nonFlammableGases(7),
#     toxicGases(8),
#     flammableLiquids(9),
#     flammableSolids(10),
#     substancesLiableToSpontaneousCombustion(11),
#     substancesEmittingFlammableGasesUponContactWithWater(12),
#     oxidizingSubstances(13),
#     organicPeroxides(14),
#     toxicSubstances(15),
#     infectiousSubstances(16),
#     radioactiveMaterial(17),
#     corrosiveSubstances(18),
#     miscellaneousDangerousSubstances(19)
# }
# ------------------------------------------------------------------------------

int64 EXPLOSIVES_1 = 0
int64 EXPLOSIVES_2 = 1
int64 EXPLOSIVES_3 = 2
int64 EXPLOSIVES_4 = 3
int64 EXPLOSIVES_5 = 4
int64 EXPLOSIVES_6 = 5
int64 FLAMMABLE_GASES = 6
int64 NON_FLAMMABLE_GASES = 7
int64 TOXIC_GASES = 8
int64 FLAMMABLE_LIQUIDS = 9
int64 FLAMMABLE_SOLIDS = 10
int64 SUBSTANCES_LIABLE_TO_SPONTANEOUS_COMBUSTION = 11
int64 SUBSTANCES_EMITTING_FLAMMABLE_GASES_UPON_CONTACT_WITH_WATER = 12
int64 OXIDIZING_SUBSTANCES = 13
int64 ORGANIC_PEROXIDES = 14
int64 TOXIC_SUBSTANCES = 15
int64 INFECTIOUS_SUBSTANCES = 16
int64 RADIOACTIVE_MATERIAL = 17
int64 CORROSIVE_SUBSTANCES = 18
int64 MISCELLANEOUS_DANGEROUS_SUBSTANCES = 19
int64 value
