# ------------------------------------------------------------------------------
# DeltaLatitude ::= INTEGER {oneMicrodegreeNorth (10), oneMicrodegreeSouth (-10) , unavailable(131072)} (-131071..131072)
# ------------------------------------------------------------------------------

int64 MIN = -131071
int64 MAX = 131072
int64 ONE_MICRODEGREE_NORTH = 10
int64 ONE_MICRODEGREE_SOUTH = -10
int64 UNAVAILABLE = 131072
int64 value
