# ------------------------------------------------------------------------------
# DeltaReferencePosition ::= SEQUENCE {
#     deltaLatitude DeltaLatitude,
#     deltaLongitude DeltaLongitude,
#     deltaAltitude DeltaAltitude
# }
# ------------------------------------------------------------------------------

DeltaLatitude delta_latitude

DeltaLongitude delta_longitude

DeltaAltitude delta_altitude

