# ------------------------------------------------------------------------------
# EventPoint ::= SEQUENCE {
#     eventPosition DeltaReferencePosition,
#     eventDeltaTime PathDeltaTime OPTIONAL,
#     informationQuality InformationQuality
# }
# ------------------------------------------------------------------------------

DeltaReferencePosition eventPosition

# optional: True
PathDeltaTime eventDeltaTime

InformationQuality informationQuality
