# ------------------------------------------------------------------------------
# HeadingValue ::= INTEGER {wgs84North(0), wgs84East(900), wgs84South(1800), wgs84West(2700), unavailable(3601)} (0..3601)
# ------------------------------------------------------------------------------

int64 MIN = 0
int64 MAX = 3601
int64 WGS_8_4_NORTH = 0
int64 WGS_8_4_EAST = 900
int64 WGS_8_4_SOUTH = 1800
int64 WGS_8_4_WEST = 2700
int64 UNAVAILABLE = 3601
int64 value
