# ------------------------------------------------------------------------------
# LanePosition::= INTEGER {offTheRoad(-1), hardShoulder(0),
# outermostDrivingLane(1), secondLaneFromOutside(2)} (-1..14)
# ------------------------------------------------------------------------------

int8 value
int8 MIN = -1
int8 MAX = 14
int8 OFF_THE_ROAD = -1
int8 HARD_SHOULDER = 0
int8 OUTERMOST_DRIVING_LANE = 1
int8 SECOND_LANE_FROM_OUTSIDE = 2

