# ------------------------------------------------------------------------------
# LateralAcceleration ::= SEQUENCE {
#     lateralAccelerationValue LateralAccelerationValue,
#     lateralAccelerationConfidence AccelerationConfidence
# }
# ------------------------------------------------------------------------------

LateralAccelerationValue lateral_acceleration_value

AccelerationConfidence lateral_acceleration_confidence

