# ------------------------------------------------------------------------------
# LateralAccelerationValue ::= INTEGER {pointOneMeterPerSecSquaredToRight(-1), pointOneMeterPerSecSquaredToLeft(1), unavailable(161)} (-160 .. 161)
# ------------------------------------------------------------------------------

int16 value
int16 MIN = -160
int16 MAX = 161
int16 POINT_ONE_METER_PER_SEC_SQUARED_TO_RIGHT = -1
int16 POINT_ONE_METER_PER_SEC_SQUARED_TO_LEFT = 1
int16 UNAVAILABLE = 161

