# ------------------------------------------------------------------------------
# LateralAcceleration ::= SEQUENCE {
#     lateralAccelerationValue LateralAccelerationValue,
#     lateralAccelerationConfidence AccelerationConfidence
# }
# ------------------------------------------------------------------------------

LateralAccelerationValue lateralAccelerationValue

AccelerationConfidence lateralAccelerationConfidence

