# ------------------------------------------------------------------------------
# LateralAccelerationValue ::= INTEGER {pointOneMeterPerSecSquaredToRight(-1), pointOneMeterPerSecSquaredToLeft(1), unavailable(161)} (-160 .. 161)
# ------------------------------------------------------------------------------

int64 MIN = -160
int64 MAX = 161
int64 POINT_ONE_METER_PER_SEC_SQUARED_TO_RIGHT = -1
int64 POINT_ONE_METER_PER_SEC_SQUARED_TO_LEFT = 1
int64 UNAVAILABLE = 161
int64 value
