# ------------------------------------------------------------------------------
# Latitude ::= INTEGER {oneMicrodegreeNorth (10), oneMicrodegreeSouth (-10), unavailable(900000001)} (-900000000..900000001)
# ------------------------------------------------------------------------------

int32 value
int32 MIN = -900000000
int32 MAX = 900000001
int32 ONE_MICRODEGREE_NORTH = 10
int32 ONE_MICRODEGREE_SOUTH = -10
int32 UNAVAILABLE = 900000001

