# ------------------------------------------------------------------------------
# LongitudinalAccelerationValue ::= INTEGER {pointOneMeterPerSecSquaredForward(1), pointOneMeterPerSecSquaredBackward(-1), unavailable(161)} (-160 .. 161)
# ------------------------------------------------------------------------------

# restricted-to: [(-160, 161)]
int64 POINT_ONE_METER_PER_SEC_SQUARED_FORWARD = 1
int64 POINT_ONE_METER_PER_SEC_SQUARED_BACKWARD = -1
int64 UNAVAILABLE = 161
int64 value
