# ------------------------------------------------------------------------------
# Longitude ::= INTEGER {oneMicrodegreeEast (10), oneMicrodegreeWest (-10), unavailable(1800000001)} (-1800000000..1800000001)
# ------------------------------------------------------------------------------

int64 MIN = -1800000000
int64 MAX = 1800000001
int64 ONE_MICRODEGREE_EAST = 10
int64 ONE_MICRODEGREE_WEST = -10
int64 UNAVAILABLE = 1800000001
int64 value
