# ------------------------------------------------------------------------------
# LongitudinalAccelerationValue ::= INTEGER {pointOneMeterPerSecSquaredForward(1), pointOneMeterPerSecSquaredBackward(-1), unavailable(161)} (-160 .. 161)
# ------------------------------------------------------------------------------

int64 MIN = -160
int64 MAX = 161
int64 POINT_ONE_METER_PER_SEC_SQUARED_FORWARD = 1
int64 POINT_ONE_METER_PER_SEC_SQUARED_BACKWARD = -1
int64 UNAVAILABLE = 161
int64 value
