# ------------------------------------------------------------------------------
# LongitudinalAcceleration ::= SEQUENCE {
#     longitudinalAccelerationValue LongitudinalAccelerationValue,
#     longitudinalAccelerationConfidence AccelerationConfidence
# }
# ------------------------------------------------------------------------------

LongitudinalAccelerationValue longitudinal_acceleration_value

AccelerationConfidence longitudinal_acceleration_confidence

