# ------------------------------------------------------------------------------
# PosConfidenceEllipse ::= SEQUENCE {
#     semiMajorConfidence SemiAxisLength,
#     semiMinorConfidence SemiAxisLength,
#     semiMajorOrientation HeadingValue
# }
# ------------------------------------------------------------------------------

SemiAxisLength semi_major_confidence

SemiAxisLength semi_minor_confidence

HeadingValue semi_major_orientation

