# ------------------------------------------------------------------------------
# PtActivationType ::= INTEGER {undefinedCodingType(0), r09-16CodingType(1), vdv-50149CodingType(2)} (0..255)
# ------------------------------------------------------------------------------

uint8 value
uint8 MIN = 0
uint8 MAX = 255
uint8 UNDEFINED_CODING_TYPE = 0
uint8 R_09_16_CODING_TYPE = 1
uint8 VDV_50149_CODING_TYPE = 2

