# ------------------------------------------------------------------------------
# PtActivationType ::= INTEGER {undefinedCodingType(0), r09-16CodingType(1), vdv-50149CodingType(2)} (0..255)
# ------------------------------------------------------------------------------

int64 MIN = 0
int64 MAX = 255
int64 UNDEFINED_CODING_TYPE = 0
int64 R_0_9_1_6_CODING_TYPE = 1
int64 VDV_5_0_1_4_9_CODING_TYPE = 2
int64 value
