# ------------------------------------------------------------------------------
# ReferencePosition ::= SEQUENCE {
#     latitude Latitude,
#     longitude Longitude,
#     positionConfidenceEllipse PosConfidenceEllipse ,
#     altitude Altitude
# }
# ------------------------------------------------------------------------------

Latitude latitude

Longitude longitude

PosConfidenceEllipse position_confidence_ellipse

Altitude altitude

