# ------------------------------------------------------------------------------
# SpecialTransportType ::= BIT STRING {heavyLoad(0), excessWidth(1), excessLength(2), excessHeight(3)} (SIZE(4))
# ------------------------------------------------------------------------------

# named-bits: [('heavyLoad', '0'), ('excessWidth', '1'), ('excessLength', '2'), ('excessHeight', '3')]
# size: [4]
uint8[] value
