# ------------------------------------------------------------------------------
# StationType ::= INTEGER {unknown(0), pedestrian(1), cyclist(2), moped(3), motorcycle(4), passengerCar(5), bus(6), 
# lightTruck(7), heavyTruck(8), trailer(9), specialVehicles(10), tram(11), roadSideUnit(15)} (0..255)
# ------------------------------------------------------------------------------

int64 MIN = 0
int64 MAX = 255
int64 UNKNOWN = 0
int64 PEDESTRIAN = 1
int64 CYCLIST = 2
int64 MOPED = 3
int64 MOTORCYCLE = 4
int64 PASSENGER_CAR = 5
int64 BUS = 6
int64 LIGHT_TRUCK = 7
int64 HEAVY_TRUCK = 8
int64 TRAILER = 9
int64 SPECIAL_VEHICLES = 10
int64 TRAM = 11
int64 ROAD_SIDE_UNIT = 15
int64 value
