# ------------------------------------------------------------------------------
# SteeringWheelAngle ::= SEQUENCE {
#     steeringWheelAngleValue SteeringWheelAngleValue,
#     steeringWheelAngleConfidence SteeringWheelAngleConfidence
# }
# ------------------------------------------------------------------------------

SteeringWheelAngleValue steeringWheelAngleValue

SteeringWheelAngleConfidence steeringWheelAngleConfidence

