# ------------------------------------------------------------------------------
# SteeringWheelAngle ::= SEQUENCE {
#     steeringWheelAngleValue SteeringWheelAngleValue,
#     steeringWheelAngleConfidence SteeringWheelAngleConfidence
# }
# ------------------------------------------------------------------------------

SteeringWheelAngleValue steering_wheel_angle_value

SteeringWheelAngleConfidence steering_wheel_angle_confidence

