# ------------------------------------------------------------------------------
# SteeringWheelAngleConfidence ::= INTEGER {equalOrWithinOnePointFiveDegree (1), outOfRange(126), unavailable(127)} (1..127)
# ------------------------------------------------------------------------------

# restricted-to: [(1, 127)]
int64 EQUAL_OR_WITHIN_ONE_POINT_FIVE_DEGREE = 1
int64 OUT_OF_RANGE = 126
int64 UNAVAILABLE = 127
int64 value
