# ------------------------------------------------------------------------------
# VehicleLength ::= SEQUENCE {
#     vehicleLengthValue VehicleLengthValue,
#     vehicleLengthConfidenceIndication VehicleLengthConfidenceIndication
# }
# ------------------------------------------------------------------------------

VehicleLengthValue vehicle_length_value

VehicleLengthConfidenceIndication vehicle_length_confidence_indication

