# ------------------------------------------------------------------------------
# VehicleLengthConfidenceIndication ::= ENUMERATED {noTrailerPresent(0), trailerPresentWithKnownLength(1), trailerPresentWithUnknownLength(2), trailerPresenceIsUnknown(3), unavailable(4)}
# ------------------------------------------------------------------------------

int64 NO_TRAILER_PRESENT = 0
int64 TRAILER_PRESENT_WITH_KNOWN_LENGTH = 1
int64 TRAILER_PRESENT_WITH_UNKNOWN_LENGTH = 2
int64 TRAILER_PRESENCE_IS_UNKNOWN = 3
int64 UNAVAILABLE = 4
int64 value
