# ------------------------------------------------------------------------------
# VehicleRole ::= ENUMERATED {default(0), publicTransport(1), specialTransport(2), dangerousGoods(3), roadWork(4), rescue(5), emergency(6), safetyCar(7), agriculture(8), commercial(9), military(10), roadOperator(11), taxi(12), reserved1(13), reserved2(14), reserved3(15)}
# ------------------------------------------------------------------------------

int64 DEFAULT = 0
int64 PUBLIC_TRANSPORT = 1
int64 SPECIAL_TRANSPORT = 2
int64 DANGEROUS_GOODS = 3
int64 ROAD_WORK = 4
int64 RESCUE = 5
int64 EMERGENCY = 6
int64 SAFETY_CAR = 7
int64 AGRICULTURE = 8
int64 COMMERCIAL = 9
int64 MILITARY = 10
int64 ROAD_OPERATOR = 11
int64 TAXI = 12
int64 RESERVED_1 = 13
int64 RESERVED_2 = 14
int64 RESERVED_3 = 15
int64 value
