# ------------------------------------------------------------------------------
# VerticalAcceleration ::= SEQUENCE {
#     verticalAccelerationValue VerticalAccelerationValue,
#     verticalAccelerationConfidence AccelerationConfidence
# }
# ------------------------------------------------------------------------------

VerticalAccelerationValue vertical_acceleration_value

AccelerationConfidence vertical_acceleration_confidence

