# ------------------------------------------------------------------------------
# VerticalAcceleration ::= SEQUENCE {
#     verticalAccelerationValue VerticalAccelerationValue,
#     verticalAccelerationConfidence AccelerationConfidence
# }
# ------------------------------------------------------------------------------

VerticalAccelerationValue verticalAccelerationValue

AccelerationConfidence verticalAccelerationConfidence
