# ------------------------------------------------------------------------------
# YawRateConfidence ::= ENUMERATED {
#     degSec-000-01 (0),
#     degSec-000-05 (1),
#     degSec-000-10 (2),
#     degSec-001-00 (3),
#     degSec-005-00 (4),
#     degSec-010-00 (5),
#     degSec-100-00 (6),
#     outOfRange (7),
#     unavailable (8)
# }
# ------------------------------------------------------------------------------

uint8 value
uint8 DEG_SEC_000_01 = 0
uint8 DEG_SEC_000_05 = 1
uint8 DEG_SEC_000_10 = 2
uint8 DEG_SEC_001_00 = 3
uint8 DEG_SEC_005_00 = 4
uint8 DEG_SEC_010_00 = 5
uint8 DEG_SEC_100_00 = 6
uint8 OUT_OF_RANGE = 7
uint8 UNAVAILABLE = 8

