// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/cam_ts103900/CAM-PDU-Descriptions.asn \
  asn1/patched/cam_ts103900/cdd/ETSI-ITS-CDD.asn \
  -t \
  cam_ts \
  -o \
  etsi_its_conversion/etsi_its_cam_ts_conversion/include/etsi_its_cam_ts_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
*
 * This DF indicates the horizontal position confidence ellipse which represents the estimated accuracy with a 
 * confidence level of 95 %. The centre of the ellipse shape corresponds to the reference
 * position point for which the position accuracy is evaluated.
 *
 * It shall include the following components: 
 *
 * @field semiMajorAxisLength: half of length of the major axis, i.e. distance between the centre point
 * and major axis point of the position accuracy ellipse. 
 *
 * @field semiMinorAxisLength: half of length of the minor axis, i.e. distance between the centre point
 * and minor axis point of the position accuracy ellipse. 
 *
 * @field semiMajorAxisOrientation: orientation direction of the ellipse major axis of the position accuracy
 * ellipse with regards to the WGS84 north. 
 * The specific WGS84 coordinate system is specified by the corresponding standards applying this DE.
 *
 * @category GeoReference information
 * @revision: created in V2.1.1 based on @ref PosConfidenceEllipse
 *
PositionConfidenceEllipse ::= SEQUENCE {
    semiMajorAxisLength         SemiAxisLength,
    semiMinorAxisLength         SemiAxisLength,
    semiMajorAxisOrientation    Wgs84AngleValue
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_cam_ts_coding/cam_ts_PositionConfidenceEllipse.h>
#include <etsi_its_cam_ts_conversion/convertSemiAxisLength.h>
#include <etsi_its_cam_ts_conversion/convertWgs84AngleValue.h>
#include <etsi_its_cam_ts_msgs/msg/position_confidence_ellipse.hpp>
namespace cam_ts_msgs = etsi_its_cam_ts_msgs::msg;


namespace etsi_its_cam_ts_conversion {

void toRos_PositionConfidenceEllipse(const cam_ts_PositionConfidenceEllipse_t& in, cam_ts_msgs::PositionConfidenceEllipse& out) {
  toRos_SemiAxisLength(in.semiMajorAxisLength, out.semi_major_axis_length);
  toRos_SemiAxisLength(in.semiMinorAxisLength, out.semi_minor_axis_length);
  toRos_Wgs84AngleValue(in.semiMajorAxisOrientation, out.semi_major_axis_orientation);
}

void toStruct_PositionConfidenceEllipse(const cam_ts_msgs::PositionConfidenceEllipse& in, cam_ts_PositionConfidenceEllipse_t& out) {
  memset(&out, 0, sizeof(cam_ts_PositionConfidenceEllipse_t));
  toStruct_SemiAxisLength(in.semi_major_axis_length, out.semiMajorAxisLength);
  toStruct_SemiAxisLength(in.semi_minor_axis_length, out.semiMinorAxisLength);
  toStruct_Wgs84AngleValue(in.semi_major_axis_orientation, out.semiMajorAxisOrientation);
}

}
