// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/cam_ts103900/CAM-PDU-Descriptions.asn \
  asn1/patched/cam_ts103900/cdd/ETSI-ITS-CDD.asn \
  -t \
  cam_ts \
  -o \
  etsi_its_conversion/etsi_its_cam_ts_conversion/include/etsi_its_cam_ts_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
*
 * The DE describes whether the yaw rate is used to calculate the curvature for a curvature value.
 * 
 * The value shall be set to:
 * - 0 - `yawRateUsed`    - if the yaw rate is used,
 * - 1 - `yawRateNotUsed` - if the yaw rate is not used,
 * - 2 - `unavailable`    - if the information of curvature calculation mode is unknown.
 *
 * @category: Vehicle information
 * @revision: V1.3.1
 *
CurvatureCalculationMode ::= ENUMERATED {
    yawRateUsed    (0), 
    yawRateNotUsed (1), 
    unavailable    (2), 
    ...
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_cam_ts_coding/cam_ts_CurvatureCalculationMode.h>

#include <etsi_its_cam_ts_msgs/msg/curvature_calculation_mode.hpp>
namespace cam_ts_msgs = etsi_its_cam_ts_msgs::msg;


namespace etsi_its_cam_ts_conversion {

void toRos_CurvatureCalculationMode(const cam_ts_CurvatureCalculationMode_t& in, cam_ts_msgs::CurvatureCalculationMode& out) {
  out.value = in;
}

void toStruct_CurvatureCalculationMode(const cam_ts_msgs::CurvatureCalculationMode& in, cam_ts_CurvatureCalculationMode_t& out) {
  memset(&out, 0, sizeof(cam_ts_CurvatureCalculationMode_t));
  out = in.value;
}

}
