# ------------------------------------------------------------------------------
# AdverseWeatherCondition-PrecipitationSubCauseCode ::= INTEGER {unavailable(0), heavyRain(1), heavySnowfall(2), softHail(3)} (0..255)
# ------------------------------------------------------------------------------

# restricted-to: [(0, 255)]
uint8 UNAVAILABLE = 0
uint8 HEAVY_RAIN = 1
uint8 HEAVY_SNOWFALL = 2
uint8 SOFT_HAIL = 3
uint8 value
