# ------------------------------------------------------------------------------
# HazardousLocation-AnimalOnTheRoadSubCauseCode ::= INTEGER {unavailable(0), wildAnimals(1), herdOfAnimals(2), smallAnimals(3), largeAnimals(4)} (0..255)
# ------------------------------------------------------------------------------

# restricted-to: [(0, 255)]
uint8 UNAVAILABLE = 0
uint8 WILD_ANIMALS = 1
uint8 HERD_OF_ANIMALS = 2
uint8 SMALL_ANIMALS = 3
uint8 LARGE_ANIMALS = 4
uint8 value
