# ------------------------------------------------------------------------------
# RoadType ::= ENUMERATED {
#     urban-NoStructuralSeparationToOppositeLanes(0),
#     urban-WithStructuralSeparationToOppositeLanes(1),
#     nonUrban-NoStructuralSeparationToOppositeLanes(2),
#     nonUrban-WithStructuralSeparationToOppositeLanes(3)}
# ------------------------------------------------------------------------------

uint8 value
uint8 URBAN_NO_STRUCTURAL_SEPARATION_TO_OPPOSITE_LANES = 0
uint8 URBAN_WITH_STRUCTURAL_SEPARATION_TO_OPPOSITE_LANES = 1
uint8 NON_URBAN_NO_STRUCTURAL_SEPARATION_TO_OPPOSITE_LANES = 2
uint8 NON_URBAN_WITH_STRUCTURAL_SEPARATION_TO_OPPOSITE_LANES = 3

