# ------------------------------------------------------------------------------
# Temperature ::= INTEGER {equalOrSmallerThanMinus60Deg (-60), oneDegreeCelsius(1), equalOrGreaterThan67Deg(67)} (-60..67)
# ------------------------------------------------------------------------------

int8 value
int8 MIN = -60
int8 MAX = 67
int8 EQUAL_OR_SMALLER_THAN_MINUS_60_DEG = -60
int8 ONE_DEGREE_CELSIUS = 1
int8 EQUAL_OR_GREATER_THAN_67_DEG = 67

