/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EV-RechargingSpotReservation-PDU-Descriptions"
 * 	found in "/input/EV-RSR-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -gen-PER`
 */

#ifndef	_CancellationResponseCode_H_
#define	_CancellationResponseCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CancellationResponseCode {
	CancellationResponseCode_ok	= 0,
	CancellationResponseCode_unknown_Reservation_ID	= 1,
	CancellationResponseCode_mismatching_Reservation_Password	= 2
} e_CancellationResponseCode;

/* CancellationResponseCode */
typedef long	 CancellationResponseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CancellationResponseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CancellationResponseCode;
extern const asn_INTEGER_specifics_t asn_SPC_CancellationResponseCode_specs_1;
asn_struct_free_f CancellationResponseCode_free;
asn_struct_print_f CancellationResponseCode_print;
asn_constr_check_f CancellationResponseCode_constraint;
ber_type_decoder_f CancellationResponseCode_decode_ber;
der_type_encoder_f CancellationResponseCode_encode_der;
xer_type_decoder_f CancellationResponseCode_decode_xer;
xer_type_encoder_f CancellationResponseCode_encode_xer;
oer_type_decoder_f CancellationResponseCode_decode_oer;
oer_type_encoder_f CancellationResponseCode_encode_oer;
per_type_decoder_f CancellationResponseCode_decode_uper;
per_type_encoder_f CancellationResponseCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CancellationResponseCode_H_ */
#include <asn_internal.h>
