/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EV-RechargingSpotReservation-PDU-Descriptions"
 * 	found in "/input/EV-RSR-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -gen-PER`
 */

#ifndef	_PaymentType_H_
#define	_PaymentType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PaymentType {
	PaymentType_contract	= 0,
	PaymentType_externalIdentification	= 1
} e_PaymentType;

/* PaymentType */
typedef long	 PaymentType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PaymentType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PaymentType;
extern const asn_INTEGER_specifics_t asn_SPC_PaymentType_specs_1;
asn_struct_free_f PaymentType_free;
asn_struct_print_f PaymentType_print;
asn_constr_check_f PaymentType_constraint;
ber_type_decoder_f PaymentType_decode_ber;
der_type_encoder_f PaymentType_encode_der;
xer_type_decoder_f PaymentType_decode_xer;
xer_type_encoder_f PaymentType_encode_xer;
oer_type_decoder_f PaymentType_decode_oer;
oer_type_encoder_f PaymentType_encode_oer;
per_type_decoder_f PaymentType_decode_uper;
per_type_encoder_f PaymentType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PaymentType_H_ */
#include <asn_internal.h>
