// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/cam_en302637_2/CAM-PDU-Descriptions.asn \
  asn1/raw/cam_en302637_2/cdd/ITS-Container.asn \
  -t \
  cam \
  -o \
  etsi_its_conversion/etsi_its_cam_conversion/include/etsi_its_cam_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
GenerationDeltaTime ::= INTEGER { oneMilliSec(1) } (0..65535)
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_cam_coding/cam_GenerationDeltaTime.h>
#include <etsi_its_cam_coding/INTEGER.h>
#include <etsi_its_primitives_conversion/convertINTEGER.h>
#include <etsi_its_cam_msgs/msg/generation_delta_time.hpp>
namespace cam_msgs = etsi_its_cam_msgs::msg;


namespace etsi_its_cam_conversion {

void toRos_GenerationDeltaTime(const cam_GenerationDeltaTime_t& in, cam_msgs::GenerationDeltaTime& out) {
  etsi_its_primitives_conversion::toRos_INTEGER(in, out.value);
}

void toStruct_GenerationDeltaTime(const cam_msgs::GenerationDeltaTime& in, cam_GenerationDeltaTime_t& out) {
  memset(&out, 0, sizeof(cam_GenerationDeltaTime_t));
  etsi_its_primitives_conversion::toStruct_INTEGER(in.value, out);
}

}
