#pragma once

#include <etsi_its_cam_coding/LongitudinalAcceleration.h>
#include <etsi_its_cam_msgs/LongitudinalAcceleration.h>
#include <etsi_its_cam_conversion/convertLongitudinalAccelerationValue.h>
#include <etsi_its_cam_conversion/convertAccelerationConfidence.h>

namespace etsi_its_cam_conversion
{
	void convert_LongitudinalAccelerationtoRos(const LongitudinalAcceleration_t& _LongitudinalAcceleration_in, etsi_its_cam_msgs::LongitudinalAcceleration& _LongitudinalAcceleration_out)
	{
		convert_LongitudinalAccelerationValuetoRos(_LongitudinalAcceleration_in.longitudinalAccelerationValue, _LongitudinalAcceleration_out.longitudinalAccelerationValue);
		convert_AccelerationConfidencetoRos(_LongitudinalAcceleration_in.longitudinalAccelerationConfidence, _LongitudinalAcceleration_out.longitudinalAccelerationConfidence);
	}
	void convert_LongitudinalAccelerationtoC(const etsi_its_cam_msgs::LongitudinalAcceleration& _LongitudinalAcceleration_in, LongitudinalAcceleration_t& _LongitudinalAcceleration_out)
	{
		memset(&_LongitudinalAcceleration_out, 0, sizeof(LongitudinalAcceleration_t));
		convert_LongitudinalAccelerationValuetoC(_LongitudinalAcceleration_in.longitudinalAccelerationValue, _LongitudinalAcceleration_out.longitudinalAccelerationValue);
		convert_AccelerationConfidencetoC(_LongitudinalAcceleration_in.longitudinalAccelerationConfidence, _LongitudinalAcceleration_out.longitudinalAccelerationConfidence);
	}
}