#pragma once

#include <etsi_its_cam_coding/VehicleLengthConfidenceIndication.h>
#include <etsi_its_cam_msgs/VehicleLengthConfidenceIndication.h>

namespace etsi_its_cam_conversion
{
	etsi_its_cam_msgs::VehicleLengthConfidenceIndication convert_VehicleLengthConfidenceIndicationtoRos(const VehicleLengthConfidenceIndication_t& _VehicleLengthConfidenceIndication_in)
	{
		etsi_its_cam_msgs::VehicleLengthConfidenceIndication VehicleLengthConfidenceIndication_out;
		VehicleLengthConfidenceIndication_out.value = _VehicleLengthConfidenceIndication_in;
		return VehicleLengthConfidenceIndication_out;
	}
	VehicleLengthConfidenceIndication_t convert_VehicleLengthConfidenceIndicationtoC(const etsi_its_cam_msgs::VehicleLengthConfidenceIndication& _VehicleLengthConfidenceIndication_in)
	{
		VehicleLengthConfidenceIndication_t VehicleLengthConfidenceIndication_out;
		memset(&VehicleLengthConfidenceIndication_out, 0, sizeof(VehicleLengthConfidenceIndication_t));
		VehicleLengthConfidenceIndication_out = _VehicleLengthConfidenceIndication_in.value;
		return VehicleLengthConfidenceIndication_out;
	}
}