// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/cam_en302637_2/CAM-PDU-Descriptions.asn \
  asn1/raw/cam_en302637_2/cdd/ITS-Container.asn \
  -t \
  cam \
  -o \
  etsi_its_conversion/etsi_its_cam_conversion/include/etsi_its_cam_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
PublicTransportContainer ::= SEQUENCE {
	embarkationStatus EmbarkationStatus,
	ptActivation PtActivation OPTIONAL
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_cam_coding/cam_PublicTransportContainer.h>
#include <etsi_its_cam_conversion/convertEmbarkationStatus.h>
#include <etsi_its_cam_conversion/convertPtActivation.h>
#include <etsi_its_cam_msgs/msg/public_transport_container.hpp>
namespace cam_msgs = etsi_its_cam_msgs::msg;


namespace etsi_its_cam_conversion {

void toRos_PublicTransportContainer(const cam_PublicTransportContainer_t& in, cam_msgs::PublicTransportContainer& out) {
  toRos_EmbarkationStatus(in.embarkationStatus, out.embarkation_status);
  if (in.ptActivation) {
    toRos_PtActivation(*in.ptActivation, out.pt_activation);
    out.pt_activation_is_present = true;
  }
}

void toStruct_PublicTransportContainer(const cam_msgs::PublicTransportContainer& in, cam_PublicTransportContainer_t& out) {
  memset(&out, 0, sizeof(cam_PublicTransportContainer_t));
  toStruct_EmbarkationStatus(in.embarkation_status, out.embarkationStatus);
  if (in.pt_activation_is_present) {
    out.ptActivation = (cam_PtActivation_t*) calloc(1, sizeof(cam_PtActivation_t));
    toStruct_PtActivation(in.pt_activation, *out.ptActivation);
  }
}

}
