// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/cam_en302637_2/CAM-PDU-Descriptions.asn \
  asn1/raw/cam_en302637_2/cdd/ITS-Container.asn \
  -t \
  cam \
  -o \
  etsi_its_conversion/etsi_its_cam_conversion/include/etsi_its_cam_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
CenDsrcTollingZoneID ::= ProtectedZoneID
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_cam_coding/cam_CenDsrcTollingZoneID.h>
#include <etsi_its_cam_conversion/convertProtectedZoneID.h>
#include <etsi_its_cam_msgs/msg/cen_dsrc_tolling_zone_id.hpp>
namespace cam_msgs = etsi_its_cam_msgs::msg;


namespace etsi_its_cam_conversion {

void toRos_CenDsrcTollingZoneID(const cam_CenDsrcTollingZoneID_t& in, cam_msgs::CenDsrcTollingZoneID& out) {
  toRos_ProtectedZoneID(in, out.value);
}

void toStruct_CenDsrcTollingZoneID(const cam_msgs::CenDsrcTollingZoneID& in, cam_CenDsrcTollingZoneID_t& out) {
  memset(&out, 0, sizeof(cam_CenDsrcTollingZoneID_t));
  toStruct_ProtectedZoneID(in.value, out);
}

}
