#pragma once

#include <etsi_its_cam_coding/BasicVehicleContainerLowFrequency.h>
#include <etsi_its_cam_msgs/BasicVehicleContainerLowFrequency.h>
#include <etsi_its_cam_conversion/convertVehicleRole.h>
#include <etsi_its_cam_conversion/convertExteriorLights.h>
#include <etsi_its_cam_conversion/convertPathHistory.h>

namespace etsi_its_cam_conversion
{
	void convert_BasicVehicleContainerLowFrequencytoRos(const BasicVehicleContainerLowFrequency_t& _BasicVehicleContainerLowFrequency_in, etsi_its_cam_msgs::BasicVehicleContainerLowFrequency& _BasicVehicleContainerLowFrequency_out)
	{
		convert_VehicleRoletoRos(_BasicVehicleContainerLowFrequency_in.vehicleRole, _BasicVehicleContainerLowFrequency_out.vehicleRole);
		convert_ExteriorLightstoRos(_BasicVehicleContainerLowFrequency_in.exteriorLights, _BasicVehicleContainerLowFrequency_out.exteriorLights);
		convert_PathHistorytoRos(_BasicVehicleContainerLowFrequency_in.pathHistory, _BasicVehicleContainerLowFrequency_out.pathHistory);
	}
	void convert_BasicVehicleContainerLowFrequencytoC(const etsi_its_cam_msgs::BasicVehicleContainerLowFrequency& _BasicVehicleContainerLowFrequency_in, BasicVehicleContainerLowFrequency_t& _BasicVehicleContainerLowFrequency_out)
	{
		memset(&_BasicVehicleContainerLowFrequency_out, 0, sizeof(BasicVehicleContainerLowFrequency_t));
		convert_VehicleRoletoC(_BasicVehicleContainerLowFrequency_in.vehicleRole, _BasicVehicleContainerLowFrequency_out.vehicleRole);
		convert_ExteriorLightstoC(_BasicVehicleContainerLowFrequency_in.exteriorLights, _BasicVehicleContainerLowFrequency_out.exteriorLights);
		convert_PathHistorytoC(_BasicVehicleContainerLowFrequency_in.pathHistory, _BasicVehicleContainerLowFrequency_out.pathHistory);
	}
}