// SPDX-License-Identifier: MIT
// Copyright Institute for Automotive Engineering (ika), RWTH Aachen University

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/cam_en302637_2/CAM-PDU-Descriptions.asn \
  asn1/raw/cam_en302637_2/cdd/ITS-Container.asn \
  -t \
  cam \
  -o \
  etsi_its_conversion/etsi_its_cam_conversion/include/etsi_its_cam_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
HardShoulderStatus ::= ENUMERATED {availableForStopping(0), closed(1), availableForDriving(2)}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_cam_coding/cam_HardShoulderStatus.h>

#include <etsi_its_cam_msgs/msg/hard_shoulder_status.hpp>
namespace cam_msgs = etsi_its_cam_msgs::msg;


namespace etsi_its_cam_conversion {

void toRos_HardShoulderStatus(const cam_HardShoulderStatus_t& in, cam_msgs::HardShoulderStatus& out) {
  out.value = in;
}

void toStruct_HardShoulderStatus(const cam_msgs::HardShoulderStatus& in, cam_HardShoulderStatus_t& out) {
  memset(&out, 0, sizeof(cam_HardShoulderStatus_t));
  out = in.value;
}

}
