# restricted-to: [(0, 255)]
int32 protocolVersion

# restricted-to: [(0, 255)]
int32 messageID
int32 MESSAGE_I_D_DENM = 1
int32 MESSAGE_I_D_CAM = 2
int32 MESSAGE_I_D_POI = 3
int32 MESSAGE_I_D_SPATEM = 4
int32 MESSAGE_I_D_MAPEM = 5
int32 MESSAGE_I_D_IVIM = 6
int32 MESSAGE_I_D_EV-RSR = 7
int32 MESSAGE_I_D_TISTPGTRANSACTION = 8
int32 MESSAGE_I_D_SREM = 9
int32 MESSAGE_I_D_SSEM = 10
int32 MESSAGE_I_D_EVCSN = 11
int32 MESSAGE_I_D_SAEM = 12
int32 MESSAGE_I_D_RTCMEM = 13

# restricted-to: [(0, 4294967295)]
int32 stationID

