# restricted-to: [(0, 255)]
uint8 protocolVersion

# restricted-to: [(0, 255)]
uint8 MESSAGE_I_D_DENM = 1
uint8 MESSAGE_I_D_CAM = 2
uint8 MESSAGE_I_D_POI = 3
uint8 MESSAGE_I_D_SPATEM = 4
uint8 MESSAGE_I_D_MAPEM = 5
uint8 MESSAGE_I_D_IVIM = 6
uint8 MESSAGE_I_D_EVRSR = 7
uint8 MESSAGE_I_D_TISTPGTRANSACTION = 8
uint8 MESSAGE_I_D_SREM = 9
uint8 MESSAGE_I_D_SSEM = 10
uint8 MESSAGE_I_D_EVCSN = 11
uint8 MESSAGE_I_D_SAEM = 12
uint8 MESSAGE_I_D_RTCMEM = 13
uint8 messageID

StationID stationID

