# named-bits: [('row1LeftOccupied', '0'), ('row1RightOccupied', '1'), ('row1MidOccupied', '2'), ('row1NotDetectable', '3'), ('row1NotPresent', '4'), ('row2LeftOccupied', '5'), ('row2RightOccupied', '6'), ('row2MidOccupied', '7'), ('row2NotDetectable', '8'), ('row2NotPresent', '9'), ('row3LeftOccupied', '10'), ('row3RightOccupied', '11'), ('row3MidOccupied', '12'), ('row3NotDetectable', '13'), ('row3NotPresent', '14'), ('row4LeftOccupied', '15'), ('row4RightOccupied', '16'), ('row4MidOccupied', '17'), ('row4NotDetectable', '18'), ('row4NotPresent', '19')]
# size: [20]
string value
