# ------------------------------------------------------------------------------
# CancellationRequestMessage ::= SEQUENCE {
#  reservation-ID				Reservation-ID,
#  reservation-Password		Reservation-Password,
#  currentTime					TimestampUTC,
#  ...
# }
# ------------------------------------------------------------------------------

Reservation_ID reservation_ID

Reservation_Password reservation_Password

TimestampUTC currentTime
