name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Get latest release tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true
        id: get-latest-tag
      - name: Export DOXYGEN_PROJECT_NUMBER
        run: echo "DOXYGEN_PROJECT_NUMBER=${{ steps.get-latest-tag.outputs.tag }}" >> $GITHUB_ENV
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          working-directory: doc
          doxyfile-path: Doxyfile
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/html