name: industrial_ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  industrial_ci:
    name: ROS ${{ matrix.ROS_DISTRO }} (${{ matrix.ROS_REPO }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ROS_DISTRO:
          - humble
          - jazzy
          - kilted
        ROS_REPO:
          - main
    steps:
      - uses: actions/checkout@v3
      - uses: ros-industrial/industrial_ci@master
        with:
          config: ${{ toJSON(matrix) }}
