/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=denm_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_H_
#define	_denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_H_


#include <etsi_its_denm_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_denm_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode {
	denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_unavailable	= 0,
	denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_emergencyVehicles	= 1,
	denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_rescueHelicopterLanding	= 2,
	denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_policeActivityOngoing	= 3,
	denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_medicalEmergencyOngoing	= 4,
	denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_childAbductionInProgress	= 5,
	denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_prioritizedVehicle	= 6,
	denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_rescueAndRecoveryVehicle	= 7
} e_denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode;

/* denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode */
typedef long	 denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode;
asn_struct_free_f denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_free;
asn_struct_print_f denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_print;
asn_constr_check_f denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_constraint;
jer_type_encoder_f denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_encode_jer;
per_type_decoder_f denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_decode_uper;
per_type_encoder_f denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_encode_uper;
per_type_decoder_f denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_decode_aper;
per_type_encoder_f denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _denm_ts_RescueAndRecoveryWorkInProgressSubCauseCode_H_ */
#include <etsi_its_denm_ts_coding/asn_internal.h>
