/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=denm_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_denm_ts_PerceivedObject_H_
#define	_denm_ts_PerceivedObject_H_


#include <etsi_its_denm_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_denm_ts_coding/denm_ts_Identifier2B.h"
#include "etsi_its_denm_ts_coding/denm_ts_DeltaTimeMilliSecondSigned.h"
#include "etsi_its_denm_ts_coding/denm_ts_CartesianPosition3dWithConfidence.h"
#include "etsi_its_denm_ts_coding/denm_ts_ObjectPerceptionQuality.h"
#include <etsi_its_denm_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct denm_ts_Velocity3dWithConfidence;
struct denm_ts_Acceleration3dWithConfidence;
struct denm_ts_EulerAnglesWithConfidence;
struct denm_ts_CartesianAngularVelocityComponent;
struct denm_ts_LowerTriangularPositiveSemidefiniteMatrices;
struct denm_ts_ObjectDimension;
struct denm_ts_SequenceOfIdentifier1B;
struct denm_ts_ObjectClassDescription;
struct denm_ts_MapPosition;

/* denm_ts_PerceivedObject */
typedef struct denm_ts_PerceivedObject {
	denm_ts_Identifier2B_t	*objectId;	/* OPTIONAL */
	denm_ts_DeltaTimeMilliSecondSigned_t	 measurementDeltaTime;
	denm_ts_CartesianPosition3dWithConfidence_t	 position;
	struct denm_ts_Velocity3dWithConfidence	*velocity;	/* OPTIONAL */
	struct denm_ts_Acceleration3dWithConfidence	*acceleration;	/* OPTIONAL */
	struct denm_ts_EulerAnglesWithConfidence	*angles;	/* OPTIONAL */
	struct denm_ts_CartesianAngularVelocityComponent	*zAngularVelocity;	/* OPTIONAL */
	struct denm_ts_LowerTriangularPositiveSemidefiniteMatrices	*lowerTriangularCorrelationMatrices;	/* OPTIONAL */
	struct denm_ts_ObjectDimension	*objectDimensionZ;	/* OPTIONAL */
	struct denm_ts_ObjectDimension	*objectDimensionY;	/* OPTIONAL */
	struct denm_ts_ObjectDimension	*objectDimensionX;	/* OPTIONAL */
	denm_ts_DeltaTimeMilliSecondSigned_t	*objectAge;	/* OPTIONAL */
	denm_ts_ObjectPerceptionQuality_t	*objectPerceptionQuality;	/* OPTIONAL */
	struct denm_ts_SequenceOfIdentifier1B	*sensorIdList;	/* OPTIONAL */
	struct denm_ts_ObjectClassDescription	*classification;	/* OPTIONAL */
	struct denm_ts_MapPosition	*mapPosition;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} denm_ts_PerceivedObject_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_denm_ts_PerceivedObject;
extern asn_SEQUENCE_specifics_t asn_SPC_denm_ts_PerceivedObject_specs_1;
extern asn_TYPE_member_t asn_MBR_denm_ts_PerceivedObject_1[16];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_denm_ts_coding/denm_ts_Velocity3dWithConfidence.h"
#include "etsi_its_denm_ts_coding/denm_ts_Acceleration3dWithConfidence.h"
#include "etsi_its_denm_ts_coding/denm_ts_EulerAnglesWithConfidence.h"
#include "etsi_its_denm_ts_coding/denm_ts_CartesianAngularVelocityComponent.h"
#include "etsi_its_denm_ts_coding/denm_ts_LowerTriangularPositiveSemidefiniteMatrices.h"
#include "etsi_its_denm_ts_coding/denm_ts_ObjectDimension.h"
#include "etsi_its_denm_ts_coding/denm_ts_SequenceOfIdentifier1B.h"
#include "etsi_its_denm_ts_coding/denm_ts_ObjectClassDescription.h"
#include "etsi_its_denm_ts_coding/denm_ts_MapPosition.h"

#endif	/* _denm_ts_PerceivedObject_H_ */
#include <etsi_its_denm_ts_coding/asn_internal.h>
