# ------------------------------------------------------------------------------
# NodeAttributeSet-addGrpC  ::=	SEQUENCE { 
#   ptvRequest  PtvRequestType  OPTIONAL,
#   nodeLink    NodeLink        OPTIONAL,
#   node        Node            OPTIONAL,
#   ...
# }
# ------------------------------------------------------------------------------

# optional: True
PtvRequestType ptvRequest

# optional: True
NodeLink nodeLink

# optional: True
Node node
