# ------------------------------------------------------------------------------
# PrioritizationResponse ::=	SEQUENCE {
#   stationID    StationID,
#   priorState   PrioritizationResponseStatus,
#   signalGroup  SignalGroupID,
#   ...
# }
# ------------------------------------------------------------------------------

StationID stationID

PrioritizationResponseStatus priorState

SignalGroupID signalGroup
